/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.otps.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostQuoteOtpRequest.Builder.class)
public final class PostQuoteOtpRequest {
    private final String email;

    private final String phone;

    private final String ownerId;

    private final Map<String, Object> additionalProperties;

    private PostQuoteOtpRequest(String email, String phone, String ownerId, Map<String, Object> additionalProperties) {
        this.email = email;
        this.phone = phone;
        this.ownerId = ownerId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Email address of the car owner
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return Phone number starting with 05 and containing 10 digits
     */
    @JsonProperty("phone")
    public String getPhone() {
        return phone;
    }

    /**
     * @return National ID or Iqama ID of the car owner (10 digits)
     */
    @JsonProperty("owner_id")
    public String getOwnerId() {
        return ownerId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostQuoteOtpRequest && equalTo((PostQuoteOtpRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostQuoteOtpRequest other) {
        return email.equals(other.email) && phone.equals(other.phone) && ownerId.equals(other.ownerId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.email, this.phone, this.ownerId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmailStage builder() {
        return new Builder();
    }

    public interface EmailStage {
        /**
         * <p>Email address of the car owner</p>
         */
        PhoneStage email(@NotNull String email);

        Builder from(PostQuoteOtpRequest other);
    }

    public interface PhoneStage {
        /**
         * <p>Phone number starting with 05 and containing 10 digits</p>
         */
        OwnerIdStage phone(@NotNull String phone);
    }

    public interface OwnerIdStage {
        /**
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         */
        _FinalStage ownerId(@NotNull String ownerId);
    }

    public interface _FinalStage {
        PostQuoteOtpRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EmailStage, PhoneStage, OwnerIdStage, _FinalStage {
        private String email;

        private String phone;

        private String ownerId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostQuoteOtpRequest other) {
            email(other.getEmail());
            phone(other.getPhone());
            ownerId(other.getOwnerId());
            return this;
        }

        /**
         * <p>Email address of the car owner</p>
         * <p>Email address of the car owner</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public PhoneStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>Phone number starting with 05 and containing 10 digits</p>
         * <p>Phone number starting with 05 and containing 10 digits</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("phone")
        public OwnerIdStage phone(@NotNull String phone) {
            this.phone = Objects.requireNonNull(phone, "phone must not be null");
            return this;
        }

        /**
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("owner_id")
        public _FinalStage ownerId(@NotNull String ownerId) {
            this.ownerId = Objects.requireNonNull(ownerId, "ownerId must not be null");
            return this;
        }

        @java.lang.Override
        public PostQuoteOtpRequest build() {
            return new PostQuoteOtpRequest(email, phone, ownerId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
