/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.otps.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostIssueOtpRequest.Builder.class)
public final class PostIssueOtpRequest {
    private final String email;

    private final String phone;

    private final String ownerId;

    private final int quoteRequestId;

    private final String quoteReferenceId;

    private final String quotePriceId;

    private final Map<String, Object> additionalProperties;

    private PostIssueOtpRequest(
            String email,
            String phone,
            String ownerId,
            int quoteRequestId,
            String quoteReferenceId,
            String quotePriceId,
            Map<String, Object> additionalProperties) {
        this.email = email;
        this.phone = phone;
        this.ownerId = ownerId;
        this.quoteRequestId = quoteRequestId;
        this.quoteReferenceId = quoteReferenceId;
        this.quotePriceId = quotePriceId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Email address of the car owner
     */
    @JsonProperty("email")
    public String getEmail() {
        return email;
    }

    /**
     * @return Phone number starting with 05 and containing 10 digits
     */
    @JsonProperty("phone")
    public String getPhone() {
        return phone;
    }

    /**
     * @return National ID or Iqama ID of the car owner (10 digits)
     */
    @JsonProperty("owner_id")
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * @return ID of the car quote request
     */
    @JsonProperty("quote_request_id")
    public int getQuoteRequestId() {
        return quoteRequestId;
    }

    /**
     * @return Unique identifier for the quote reference ID (coming from POST /quote-requests)
     */
    @JsonProperty("quote_reference_id")
    public String getQuoteReferenceId() {
        return quoteReferenceId;
    }

    /**
     * @return Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)
     */
    @JsonProperty("quote_price_id")
    public String getQuotePriceId() {
        return quotePriceId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostIssueOtpRequest && equalTo((PostIssueOtpRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostIssueOtpRequest other) {
        return email.equals(other.email)
                && phone.equals(other.phone)
                && ownerId.equals(other.ownerId)
                && quoteRequestId == other.quoteRequestId
                && quoteReferenceId.equals(other.quoteReferenceId)
                && quotePriceId.equals(other.quotePriceId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.email, this.phone, this.ownerId, this.quoteRequestId, this.quoteReferenceId, this.quotePriceId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EmailStage builder() {
        return new Builder();
    }

    public interface EmailStage {
        /**
         * <p>Email address of the car owner</p>
         */
        PhoneStage email(@NotNull String email);

        Builder from(PostIssueOtpRequest other);
    }

    public interface PhoneStage {
        /**
         * <p>Phone number starting with 05 and containing 10 digits</p>
         */
        OwnerIdStage phone(@NotNull String phone);
    }

    public interface OwnerIdStage {
        /**
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         */
        QuoteRequestIdStage ownerId(@NotNull String ownerId);
    }

    public interface QuoteRequestIdStage {
        /**
         * <p>ID of the car quote request</p>
         */
        QuoteReferenceIdStage quoteRequestId(int quoteRequestId);
    }

    public interface QuoteReferenceIdStage {
        /**
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         */
        QuotePriceIdStage quoteReferenceId(@NotNull String quoteReferenceId);
    }

    public interface QuotePriceIdStage {
        /**
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         */
        _FinalStage quotePriceId(@NotNull String quotePriceId);
    }

    public interface _FinalStage {
        PostIssueOtpRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements EmailStage,
                    PhoneStage,
                    OwnerIdStage,
                    QuoteRequestIdStage,
                    QuoteReferenceIdStage,
                    QuotePriceIdStage,
                    _FinalStage {
        private String email;

        private String phone;

        private String ownerId;

        private int quoteRequestId;

        private String quoteReferenceId;

        private String quotePriceId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostIssueOtpRequest other) {
            email(other.getEmail());
            phone(other.getPhone());
            ownerId(other.getOwnerId());
            quoteRequestId(other.getQuoteRequestId());
            quoteReferenceId(other.getQuoteReferenceId());
            quotePriceId(other.getQuotePriceId());
            return this;
        }

        /**
         * <p>Email address of the car owner</p>
         * <p>Email address of the car owner</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("email")
        public PhoneStage email(@NotNull String email) {
            this.email = Objects.requireNonNull(email, "email must not be null");
            return this;
        }

        /**
         * <p>Phone number starting with 05 and containing 10 digits</p>
         * <p>Phone number starting with 05 and containing 10 digits</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("phone")
        public OwnerIdStage phone(@NotNull String phone) {
            this.phone = Objects.requireNonNull(phone, "phone must not be null");
            return this;
        }

        /**
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         * <p>National ID or Iqama ID of the car owner (10 digits)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("owner_id")
        public QuoteRequestIdStage ownerId(@NotNull String ownerId) {
            this.ownerId = Objects.requireNonNull(ownerId, "ownerId must not be null");
            return this;
        }

        /**
         * <p>ID of the car quote request</p>
         * <p>ID of the car quote request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_request_id")
        public QuoteReferenceIdStage quoteRequestId(int quoteRequestId) {
            this.quoteRequestId = quoteRequestId;
            return this;
        }

        /**
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_reference_id")
        public QuotePriceIdStage quoteReferenceId(@NotNull String quoteReferenceId) {
            this.quoteReferenceId = Objects.requireNonNull(quoteReferenceId, "quoteReferenceId must not be null");
            return this;
        }

        /**
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_price_id")
        public _FinalStage quotePriceId(@NotNull String quotePriceId) {
            this.quotePriceId = Objects.requireNonNull(quotePriceId, "quotePriceId must not be null");
            return this;
        }

        @java.lang.Override
        public PostIssueOtpRequest build() {
            return new PostIssueOtpRequest(
                    email, phone, ownerId, quoteRequestId, quoteReferenceId, quotePriceId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
