/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetQuoteRequestsRequest.Builder.class)
public final class GetQuoteRequestsRequest {
    private final Optional<String> dateFrom;

    private final Optional<String> dateTo;

    private final Optional<Integer> perPage;

    private final Optional<Boolean> includeAggregates;

    private final Map<String, Object> additionalProperties;

    private GetQuoteRequestsRequest(
            Optional<String> dateFrom,
            Optional<String> dateTo,
            Optional<Integer> perPage,
            Optional<Boolean> includeAggregates,
            Map<String, Object> additionalProperties) {
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
        this.perPage = perPage;
        this.includeAggregates = includeAggregates;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Inclusive lower bound for quote request creation date.
     */
    @JsonProperty("date_from")
    public Optional<String> getDateFrom() {
        return dateFrom;
    }

    /**
     * @return Inclusive upper bound for quote request creation date.
     */
    @JsonProperty("date_to")
    public Optional<String> getDateTo() {
        return dateTo;
    }

    /**
     * @return Number of quote requests to return per page.
     */
    @JsonProperty("per_page")
    public Optional<Integer> getPerPage() {
        return perPage;
    }

    /**
     * @return When true, includes quote request totals and monthly buckets for the filtered result set.
     */
    @JsonProperty("include_aggregates")
    public Optional<Boolean> getIncludeAggregates() {
        return includeAggregates;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetQuoteRequestsRequest && equalTo((GetQuoteRequestsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetQuoteRequestsRequest other) {
        return dateFrom.equals(other.dateFrom)
                && dateTo.equals(other.dateTo)
                && perPage.equals(other.perPage)
                && includeAggregates.equals(other.includeAggregates);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.dateFrom, this.dateTo, this.perPage, this.includeAggregates);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> dateFrom = Optional.empty();

        private Optional<String> dateTo = Optional.empty();

        private Optional<Integer> perPage = Optional.empty();

        private Optional<Boolean> includeAggregates = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetQuoteRequestsRequest other) {
            dateFrom(other.getDateFrom());
            dateTo(other.getDateTo());
            perPage(other.getPerPage());
            includeAggregates(other.getIncludeAggregates());
            return this;
        }

        /**
         * <p>Inclusive lower bound for quote request creation date.</p>
         */
        @JsonSetter(value = "date_from", nulls = Nulls.SKIP)
        public Builder dateFrom(Optional<String> dateFrom) {
            this.dateFrom = dateFrom;
            return this;
        }

        public Builder dateFrom(String dateFrom) {
            this.dateFrom = Optional.ofNullable(dateFrom);
            return this;
        }

        /**
         * <p>Inclusive upper bound for quote request creation date.</p>
         */
        @JsonSetter(value = "date_to", nulls = Nulls.SKIP)
        public Builder dateTo(Optional<String> dateTo) {
            this.dateTo = dateTo;
            return this;
        }

        public Builder dateTo(String dateTo) {
            this.dateTo = Optional.ofNullable(dateTo);
            return this;
        }

        /**
         * <p>Number of quote requests to return per page.</p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(Optional<Integer> perPage) {
            this.perPage = perPage;
            return this;
        }

        public Builder perPage(Integer perPage) {
            this.perPage = Optional.ofNullable(perPage);
            return this;
        }

        /**
         * <p>When true, includes quote request totals and monthly buckets for the filtered result set.</p>
         */
        @JsonSetter(value = "include_aggregates", nulls = Nulls.SKIP)
        public Builder includeAggregates(Optional<Boolean> includeAggregates) {
            this.includeAggregates = includeAggregates;
            return this;
        }

        public Builder includeAggregates(Boolean includeAggregates) {
            this.includeAggregates = Optional.ofNullable(includeAggregates);
            return this;
        }

        public GetQuoteRequestsRequest build() {
            return new GetQuoteRequestsRequest(dateFrom, dateTo, perPage, includeAggregates, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
