/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import com.yasminaai.api.resources.quotes.types.PostQuoteRequestsRequestDriversItem;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostQuoteRequestsRequest.Builder.class)
public final class PostQuoteRequestsRequest {
    private final String ownerId;

    private final Optional<String> email;

    private final String phone;

    private final String birthdate;

    private final String carSequenceNumber;

    private final Optional<Boolean> isOwnershipTransfer;

    private final Optional<String> currentCarOwnerId;

    private final double carEstimatedCost;

    private final Optional<Integer> carModelYear;

    private final Optional<String> startDate;

    private final Optional<List<PostQuoteRequestsRequestDriversItem>> drivers;

    private final Map<String, Object> additionalProperties;

    private PostQuoteRequestsRequest(
            String ownerId,
            Optional<String> email,
            String phone,
            String birthdate,
            String carSequenceNumber,
            Optional<Boolean> isOwnershipTransfer,
            Optional<String> currentCarOwnerId,
            double carEstimatedCost,
            Optional<Integer> carModelYear,
            Optional<String> startDate,
            Optional<List<PostQuoteRequestsRequestDriversItem>> drivers,
            Map<String, Object> additionalProperties) {
        this.ownerId = ownerId;
        this.email = email;
        this.phone = phone;
        this.birthdate = birthdate;
        this.carSequenceNumber = carSequenceNumber;
        this.isOwnershipTransfer = isOwnershipTransfer;
        this.currentCarOwnerId = currentCarOwnerId;
        this.carEstimatedCost = carEstimatedCost;
        this.carModelYear = carModelYear;
        this.startDate = startDate;
        this.drivers = drivers;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Owner ID must be 10 digits starting with 1, 2, or 7
     */
    @JsonProperty("owner_id")
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * @return Email address must be valid and belongs to the customer
     */
    @JsonProperty("email")
    public Optional<String> getEmail() {
        return email;
    }

    /**
     * @return Phone number must start with 05 and be 10 digits
     */
    @JsonProperty("phone")
    public String getPhone() {
        return phone;
    }

    /**
     * @return Birthdate in YYYY-MM-DD format
     */
    @JsonProperty("birthdate")
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * @return Car sequence number must be 8 or 9 digits
     */
    @JsonProperty("car_sequence_number")
    public String getCarSequenceNumber() {
        return carSequenceNumber;
    }

    /**
     * @return Indicates if the ownership is being transferred
     */
    @JsonProperty("is_ownership_transfer")
    public Optional<Boolean> getIsOwnershipTransfer() {
        return isOwnershipTransfer;
    }

    /**
     * @return Required if is_ownership_transfer is true; 10 digits starting with 1,2,7
     */
    @JsonProperty("current_car_owner_id")
    public Optional<String> getCurrentCarOwnerId() {
        return currentCarOwnerId;
    }

    /**
     * @return Estimated cost of the car
     */
    @JsonProperty("car_estimated_cost")
    public double getCarEstimatedCost() {
        return carEstimatedCost;
    }

    /**
     * @return Car model year between 1950 and next year
     */
    @JsonProperty("car_model_year")
    public Optional<Integer> getCarModelYear() {
        return carModelYear;
    }

    /**
     * @return Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.
     */
    @JsonProperty("start_date")
    public Optional<String> getStartDate() {
        return startDate;
    }

    /**
     * @return List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.
     */
    @JsonProperty("drivers")
    public Optional<List<PostQuoteRequestsRequestDriversItem>> getDrivers() {
        return drivers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostQuoteRequestsRequest && equalTo((PostQuoteRequestsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostQuoteRequestsRequest other) {
        return ownerId.equals(other.ownerId)
                && email.equals(other.email)
                && phone.equals(other.phone)
                && birthdate.equals(other.birthdate)
                && carSequenceNumber.equals(other.carSequenceNumber)
                && isOwnershipTransfer.equals(other.isOwnershipTransfer)
                && currentCarOwnerId.equals(other.currentCarOwnerId)
                && carEstimatedCost == other.carEstimatedCost
                && carModelYear.equals(other.carModelYear)
                && startDate.equals(other.startDate)
                && drivers.equals(other.drivers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ownerId,
                this.email,
                this.phone,
                this.birthdate,
                this.carSequenceNumber,
                this.isOwnershipTransfer,
                this.currentCarOwnerId,
                this.carEstimatedCost,
                this.carModelYear,
                this.startDate,
                this.drivers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OwnerIdStage builder() {
        return new Builder();
    }

    public interface OwnerIdStage {
        /**
         * <p>Owner ID must be 10 digits starting with 1, 2, or 7</p>
         */
        PhoneStage ownerId(@NotNull String ownerId);

        Builder from(PostQuoteRequestsRequest other);
    }

    public interface PhoneStage {
        /**
         * <p>Phone number must start with 05 and be 10 digits</p>
         */
        BirthdateStage phone(@NotNull String phone);
    }

    public interface BirthdateStage {
        /**
         * <p>Birthdate in YYYY-MM-DD format</p>
         */
        CarSequenceNumberStage birthdate(@NotNull String birthdate);
    }

    public interface CarSequenceNumberStage {
        /**
         * <p>Car sequence number must be 8 or 9 digits</p>
         */
        CarEstimatedCostStage carSequenceNumber(@NotNull String carSequenceNumber);
    }

    public interface CarEstimatedCostStage {
        /**
         * <p>Estimated cost of the car</p>
         */
        _FinalStage carEstimatedCost(double carEstimatedCost);
    }

    public interface _FinalStage {
        PostQuoteRequestsRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Email address must be valid and belongs to the customer</p>
         */
        _FinalStage email(Optional<String> email);

        _FinalStage email(String email);

        /**
         * <p>Indicates if the ownership is being transferred</p>
         */
        _FinalStage isOwnershipTransfer(Optional<Boolean> isOwnershipTransfer);

        _FinalStage isOwnershipTransfer(Boolean isOwnershipTransfer);

        /**
         * <p>Required if is_ownership_transfer is true; 10 digits starting with 1,2,7</p>
         */
        _FinalStage currentCarOwnerId(Optional<String> currentCarOwnerId);

        _FinalStage currentCarOwnerId(String currentCarOwnerId);

        /**
         * <p>Car model year between 1950 and next year</p>
         */
        _FinalStage carModelYear(Optional<Integer> carModelYear);

        _FinalStage carModelYear(Integer carModelYear);

        /**
         * <p>Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.</p>
         */
        _FinalStage startDate(Optional<String> startDate);

        _FinalStage startDate(String startDate);

        /**
         * <p>List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.</p>
         */
        _FinalStage drivers(Optional<List<PostQuoteRequestsRequestDriversItem>> drivers);

        _FinalStage drivers(List<PostQuoteRequestsRequestDriversItem> drivers);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements OwnerIdStage,
                    PhoneStage,
                    BirthdateStage,
                    CarSequenceNumberStage,
                    CarEstimatedCostStage,
                    _FinalStage {
        private String ownerId;

        private String phone;

        private String birthdate;

        private String carSequenceNumber;

        private double carEstimatedCost;

        private Optional<List<PostQuoteRequestsRequestDriversItem>> drivers = Optional.empty();

        private Optional<String> startDate = Optional.empty();

        private Optional<Integer> carModelYear = Optional.empty();

        private Optional<String> currentCarOwnerId = Optional.empty();

        private Optional<Boolean> isOwnershipTransfer = Optional.empty();

        private Optional<String> email = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostQuoteRequestsRequest other) {
            ownerId(other.getOwnerId());
            email(other.getEmail());
            phone(other.getPhone());
            birthdate(other.getBirthdate());
            carSequenceNumber(other.getCarSequenceNumber());
            isOwnershipTransfer(other.getIsOwnershipTransfer());
            currentCarOwnerId(other.getCurrentCarOwnerId());
            carEstimatedCost(other.getCarEstimatedCost());
            carModelYear(other.getCarModelYear());
            startDate(other.getStartDate());
            drivers(other.getDrivers());
            return this;
        }

        /**
         * <p>Owner ID must be 10 digits starting with 1, 2, or 7</p>
         * <p>Owner ID must be 10 digits starting with 1, 2, or 7</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("owner_id")
        public PhoneStage ownerId(@NotNull String ownerId) {
            this.ownerId = Objects.requireNonNull(ownerId, "ownerId must not be null");
            return this;
        }

        /**
         * <p>Phone number must start with 05 and be 10 digits</p>
         * <p>Phone number must start with 05 and be 10 digits</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("phone")
        public BirthdateStage phone(@NotNull String phone) {
            this.phone = Objects.requireNonNull(phone, "phone must not be null");
            return this;
        }

        /**
         * <p>Birthdate in YYYY-MM-DD format</p>
         * <p>Birthdate in YYYY-MM-DD format</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("birthdate")
        public CarSequenceNumberStage birthdate(@NotNull String birthdate) {
            this.birthdate = Objects.requireNonNull(birthdate, "birthdate must not be null");
            return this;
        }

        /**
         * <p>Car sequence number must be 8 or 9 digits</p>
         * <p>Car sequence number must be 8 or 9 digits</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("car_sequence_number")
        public CarEstimatedCostStage carSequenceNumber(@NotNull String carSequenceNumber) {
            this.carSequenceNumber = Objects.requireNonNull(carSequenceNumber, "carSequenceNumber must not be null");
            return this;
        }

        /**
         * <p>Estimated cost of the car</p>
         * <p>Estimated cost of the car</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("car_estimated_cost")
        public _FinalStage carEstimatedCost(double carEstimatedCost) {
            this.carEstimatedCost = carEstimatedCost;
            return this;
        }

        /**
         * <p>List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage drivers(List<PostQuoteRequestsRequestDriversItem> drivers) {
            this.drivers = Optional.ofNullable(drivers);
            return this;
        }

        /**
         * <p>List of drivers for the vehicle. When provided, the sum of all driving_percentage values must equal 100, and the owner must be included among the drivers.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "drivers", nulls = Nulls.SKIP)
        public _FinalStage drivers(Optional<List<PostQuoteRequestsRequestDriversItem>> drivers) {
            this.drivers = drivers;
            return this;
        }

        /**
         * <p>Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage startDate(String startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        /**
         * <p>Desired policy start date in YYYY-MM-DD. Must be between tomorrow and 28 days from today (inclusive). The platform validates this range server-side.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public _FinalStage startDate(Optional<String> startDate) {
            this.startDate = startDate;
            return this;
        }

        /**
         * <p>Car model year between 1950 and next year</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage carModelYear(Integer carModelYear) {
            this.carModelYear = Optional.ofNullable(carModelYear);
            return this;
        }

        /**
         * <p>Car model year between 1950 and next year</p>
         */
        @java.lang.Override
        @JsonSetter(value = "car_model_year", nulls = Nulls.SKIP)
        public _FinalStage carModelYear(Optional<Integer> carModelYear) {
            this.carModelYear = carModelYear;
            return this;
        }

        /**
         * <p>Required if is_ownership_transfer is true; 10 digits starting with 1,2,7</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage currentCarOwnerId(String currentCarOwnerId) {
            this.currentCarOwnerId = Optional.ofNullable(currentCarOwnerId);
            return this;
        }

        /**
         * <p>Required if is_ownership_transfer is true; 10 digits starting with 1,2,7</p>
         */
        @java.lang.Override
        @JsonSetter(value = "current_car_owner_id", nulls = Nulls.SKIP)
        public _FinalStage currentCarOwnerId(Optional<String> currentCarOwnerId) {
            this.currentCarOwnerId = currentCarOwnerId;
            return this;
        }

        /**
         * <p>Indicates if the ownership is being transferred</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage isOwnershipTransfer(Boolean isOwnershipTransfer) {
            this.isOwnershipTransfer = Optional.ofNullable(isOwnershipTransfer);
            return this;
        }

        /**
         * <p>Indicates if the ownership is being transferred</p>
         */
        @java.lang.Override
        @JsonSetter(value = "is_ownership_transfer", nulls = Nulls.SKIP)
        public _FinalStage isOwnershipTransfer(Optional<Boolean> isOwnershipTransfer) {
            this.isOwnershipTransfer = isOwnershipTransfer;
            return this;
        }

        /**
         * <p>Email address must be valid and belongs to the customer</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage email(String email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Email address must be valid and belongs to the customer</p>
         */
        @java.lang.Override
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public _FinalStage email(Optional<String> email) {
            this.email = email;
            return this;
        }

        @java.lang.Override
        public PostQuoteRequestsRequest build() {
            return new PostQuoteRequestsRequest(
                    ownerId,
                    email,
                    phone,
                    birthdate,
                    carSequenceNumber,
                    isOwnershipTransfer,
                    currentCarOwnerId,
                    carEstimatedCost,
                    carModelYear,
                    startDate,
                    drivers,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
