/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.policies.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetPoliciesRequest.Builder.class)
public final class GetPoliciesRequest {
    private final Optional<Integer> quoteRequestId;

    private final Optional<String> quotePriceId;

    private final Optional<Integer> providerPolicyId;

    private final Optional<String> carSequenceNumber;

    private final Optional<String> newOwnerId;

    private final Optional<String> previousOwnerId;

    private final Optional<Integer> status;

    private final Optional<Double> minPrice;

    private final Optional<Double> maxPrice;

    private final Optional<Integer> perPage;

    private final Map<String, Object> additionalProperties;

    private GetPoliciesRequest(
            Optional<Integer> quoteRequestId,
            Optional<String> quotePriceId,
            Optional<Integer> providerPolicyId,
            Optional<String> carSequenceNumber,
            Optional<String> newOwnerId,
            Optional<String> previousOwnerId,
            Optional<Integer> status,
            Optional<Double> minPrice,
            Optional<Double> maxPrice,
            Optional<Integer> perPage,
            Map<String, Object> additionalProperties) {
        this.quoteRequestId = quoteRequestId;
        this.quotePriceId = quotePriceId;
        this.providerPolicyId = providerPolicyId;
        this.carSequenceNumber = carSequenceNumber;
        this.newOwnerId = newOwnerId;
        this.previousOwnerId = previousOwnerId;
        this.status = status;
        this.minPrice = minPrice;
        this.maxPrice = maxPrice;
        this.perPage = perPage;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("quote_request_id")
    public Optional<Integer> getQuoteRequestId() {
        return quoteRequestId;
    }

    @JsonProperty("quote_price_id")
    public Optional<String> getQuotePriceId() {
        return quotePriceId;
    }

    @JsonProperty("provider_policy_id")
    public Optional<Integer> getProviderPolicyId() {
        return providerPolicyId;
    }

    @JsonProperty("car_sequence_number")
    public Optional<String> getCarSequenceNumber() {
        return carSequenceNumber;
    }

    @JsonProperty("new_owner_id")
    public Optional<String> getNewOwnerId() {
        return newOwnerId;
    }

    @JsonProperty("previous_owner_id")
    public Optional<String> getPreviousOwnerId() {
        return previousOwnerId;
    }

    @JsonProperty("status")
    public Optional<Integer> getStatus() {
        return status;
    }

    @JsonProperty("min_price")
    public Optional<Double> getMinPrice() {
        return minPrice;
    }

    @JsonProperty("max_price")
    public Optional<Double> getMaxPrice() {
        return maxPrice;
    }

    @JsonProperty("per_page")
    public Optional<Integer> getPerPage() {
        return perPage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetPoliciesRequest && equalTo((GetPoliciesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetPoliciesRequest other) {
        return quoteRequestId.equals(other.quoteRequestId)
                && quotePriceId.equals(other.quotePriceId)
                && providerPolicyId.equals(other.providerPolicyId)
                && carSequenceNumber.equals(other.carSequenceNumber)
                && newOwnerId.equals(other.newOwnerId)
                && previousOwnerId.equals(other.previousOwnerId)
                && status.equals(other.status)
                && minPrice.equals(other.minPrice)
                && maxPrice.equals(other.maxPrice)
                && perPage.equals(other.perPage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.quoteRequestId,
                this.quotePriceId,
                this.providerPolicyId,
                this.carSequenceNumber,
                this.newOwnerId,
                this.previousOwnerId,
                this.status,
                this.minPrice,
                this.maxPrice,
                this.perPage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> quoteRequestId = Optional.empty();

        private Optional<String> quotePriceId = Optional.empty();

        private Optional<Integer> providerPolicyId = Optional.empty();

        private Optional<String> carSequenceNumber = Optional.empty();

        private Optional<String> newOwnerId = Optional.empty();

        private Optional<String> previousOwnerId = Optional.empty();

        private Optional<Integer> status = Optional.empty();

        private Optional<Double> minPrice = Optional.empty();

        private Optional<Double> maxPrice = Optional.empty();

        private Optional<Integer> perPage = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetPoliciesRequest other) {
            quoteRequestId(other.getQuoteRequestId());
            quotePriceId(other.getQuotePriceId());
            providerPolicyId(other.getProviderPolicyId());
            carSequenceNumber(other.getCarSequenceNumber());
            newOwnerId(other.getNewOwnerId());
            previousOwnerId(other.getPreviousOwnerId());
            status(other.getStatus());
            minPrice(other.getMinPrice());
            maxPrice(other.getMaxPrice());
            perPage(other.getPerPage());
            return this;
        }

        @JsonSetter(value = "quote_request_id", nulls = Nulls.SKIP)
        public Builder quoteRequestId(Optional<Integer> quoteRequestId) {
            this.quoteRequestId = quoteRequestId;
            return this;
        }

        public Builder quoteRequestId(Integer quoteRequestId) {
            this.quoteRequestId = Optional.ofNullable(quoteRequestId);
            return this;
        }

        @JsonSetter(value = "quote_price_id", nulls = Nulls.SKIP)
        public Builder quotePriceId(Optional<String> quotePriceId) {
            this.quotePriceId = quotePriceId;
            return this;
        }

        public Builder quotePriceId(String quotePriceId) {
            this.quotePriceId = Optional.ofNullable(quotePriceId);
            return this;
        }

        @JsonSetter(value = "provider_policy_id", nulls = Nulls.SKIP)
        public Builder providerPolicyId(Optional<Integer> providerPolicyId) {
            this.providerPolicyId = providerPolicyId;
            return this;
        }

        public Builder providerPolicyId(Integer providerPolicyId) {
            this.providerPolicyId = Optional.ofNullable(providerPolicyId);
            return this;
        }

        @JsonSetter(value = "car_sequence_number", nulls = Nulls.SKIP)
        public Builder carSequenceNumber(Optional<String> carSequenceNumber) {
            this.carSequenceNumber = carSequenceNumber;
            return this;
        }

        public Builder carSequenceNumber(String carSequenceNumber) {
            this.carSequenceNumber = Optional.ofNullable(carSequenceNumber);
            return this;
        }

        @JsonSetter(value = "new_owner_id", nulls = Nulls.SKIP)
        public Builder newOwnerId(Optional<String> newOwnerId) {
            this.newOwnerId = newOwnerId;
            return this;
        }

        public Builder newOwnerId(String newOwnerId) {
            this.newOwnerId = Optional.ofNullable(newOwnerId);
            return this;
        }

        @JsonSetter(value = "previous_owner_id", nulls = Nulls.SKIP)
        public Builder previousOwnerId(Optional<String> previousOwnerId) {
            this.previousOwnerId = previousOwnerId;
            return this;
        }

        public Builder previousOwnerId(String previousOwnerId) {
            this.previousOwnerId = Optional.ofNullable(previousOwnerId);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<Integer> status) {
            this.status = status;
            return this;
        }

        public Builder status(Integer status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        @JsonSetter(value = "min_price", nulls = Nulls.SKIP)
        public Builder minPrice(Optional<Double> minPrice) {
            this.minPrice = minPrice;
            return this;
        }

        public Builder minPrice(Double minPrice) {
            this.minPrice = Optional.ofNullable(minPrice);
            return this;
        }

        @JsonSetter(value = "max_price", nulls = Nulls.SKIP)
        public Builder maxPrice(Optional<Double> maxPrice) {
            this.maxPrice = maxPrice;
            return this;
        }

        public Builder maxPrice(Double maxPrice) {
            this.maxPrice = Optional.ofNullable(maxPrice);
            return this;
        }

        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(Optional<Integer> perPage) {
            this.perPage = perPage;
            return this;
        }

        public Builder perPage(Integer perPage) {
            this.perPage = Optional.ofNullable(perPage);
            return this;
        }

        public GetPoliciesRequest build() {
            return new GetPoliciesRequest(
                    quoteRequestId,
                    quotePriceId,
                    providerPolicyId,
                    carSequenceNumber,
                    newOwnerId,
                    previousOwnerId,
                    status,
                    minPrice,
                    maxPrice,
                    perPage,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
