/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.policies.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostPoliciesRequest.Builder.class)
public final class PostPoliciesRequest {
    private final String otp;

    private final int quoteRequestId;

    private final String quoteReferenceId;

    private final String quotePriceId;

    private final Optional<List<String>> benefits;

    private final Optional<Map<String, Object>> extraFields;

    private final Map<String, Object> additionalProperties;

    private PostPoliciesRequest(
            String otp,
            int quoteRequestId,
            String quoteReferenceId,
            String quotePriceId,
            Optional<List<String>> benefits,
            Optional<Map<String, Object>> extraFields,
            Map<String, Object> additionalProperties) {
        this.otp = otp;
        this.quoteRequestId = quoteRequestId;
        this.quoteReferenceId = quoteReferenceId;
        this.quotePriceId = quotePriceId;
        this.benefits = benefits;
        this.extraFields = extraFields;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The OTP received by the customer from the Issue OTP API
     */
    @JsonProperty("otp")
    public String getOtp() {
        return otp;
    }

    /**
     * @return ID of the car quote request
     */
    @JsonProperty("quote_request_id")
    public int getQuoteRequestId() {
        return quoteRequestId;
    }

    /**
     * @return Unique identifier for the quote reference ID (coming from POST /quote-requests)
     */
    @JsonProperty("quote_reference_id")
    public String getQuoteReferenceId() {
        return quoteReferenceId;
    }

    /**
     * @return Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)
     */
    @JsonProperty("quote_price_id")
    public String getQuotePriceId() {
        return quotePriceId;
    }

    /**
     * @return List of benefit UUIDs
     */
    @JsonProperty("benefits")
    public Optional<List<String>> getBenefits() {
        return benefits;
    }

    /**
     * @return Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.
     */
    @JsonProperty("extra_fields")
    public Optional<Map<String, Object>> getExtraFields() {
        return extraFields;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostPoliciesRequest && equalTo((PostPoliciesRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostPoliciesRequest other) {
        return otp.equals(other.otp)
                && quoteRequestId == other.quoteRequestId
                && quoteReferenceId.equals(other.quoteReferenceId)
                && quotePriceId.equals(other.quotePriceId)
                && benefits.equals(other.benefits)
                && extraFields.equals(other.extraFields);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.otp,
                this.quoteRequestId,
                this.quoteReferenceId,
                this.quotePriceId,
                this.benefits,
                this.extraFields);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OtpStage builder() {
        return new Builder();
    }

    public interface OtpStage {
        /**
         * <p>The OTP received by the customer from the Issue OTP API</p>
         */
        QuoteRequestIdStage otp(@NotNull String otp);

        Builder from(PostPoliciesRequest other);
    }

    public interface QuoteRequestIdStage {
        /**
         * <p>ID of the car quote request</p>
         */
        QuoteReferenceIdStage quoteRequestId(int quoteRequestId);
    }

    public interface QuoteReferenceIdStage {
        /**
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         */
        QuotePriceIdStage quoteReferenceId(@NotNull String quoteReferenceId);
    }

    public interface QuotePriceIdStage {
        /**
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         */
        _FinalStage quotePriceId(@NotNull String quotePriceId);
    }

    public interface _FinalStage {
        PostPoliciesRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>List of benefit UUIDs</p>
         */
        _FinalStage benefits(Optional<List<String>> benefits);

        _FinalStage benefits(List<String> benefits);

        /**
         * <p>Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.</p>
         */
        _FinalStage extraFields(Optional<Map<String, Object>> extraFields);

        _FinalStage extraFields(Map<String, Object> extraFields);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements OtpStage, QuoteRequestIdStage, QuoteReferenceIdStage, QuotePriceIdStage, _FinalStage {
        private String otp;

        private int quoteRequestId;

        private String quoteReferenceId;

        private String quotePriceId;

        private Optional<Map<String, Object>> extraFields = Optional.empty();

        private Optional<List<String>> benefits = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostPoliciesRequest other) {
            otp(other.getOtp());
            quoteRequestId(other.getQuoteRequestId());
            quoteReferenceId(other.getQuoteReferenceId());
            quotePriceId(other.getQuotePriceId());
            benefits(other.getBenefits());
            extraFields(other.getExtraFields());
            return this;
        }

        /**
         * <p>The OTP received by the customer from the Issue OTP API</p>
         * <p>The OTP received by the customer from the Issue OTP API</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("otp")
        public QuoteRequestIdStage otp(@NotNull String otp) {
            this.otp = Objects.requireNonNull(otp, "otp must not be null");
            return this;
        }

        /**
         * <p>ID of the car quote request</p>
         * <p>ID of the car quote request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_request_id")
        public QuoteReferenceIdStage quoteRequestId(int quoteRequestId) {
            this.quoteRequestId = quoteRequestId;
            return this;
        }

        /**
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         * <p>Unique identifier for the quote reference ID (coming from POST /quote-requests)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_reference_id")
        public QuotePriceIdStage quoteReferenceId(@NotNull String quoteReferenceId) {
            this.quoteReferenceId = Objects.requireNonNull(quoteReferenceId, "quoteReferenceId must not be null");
            return this;
        }

        /**
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         * <p>Unique identifier for the quote price ID that exists inside a quote item (coming from POST /quote-requests)</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("quote_price_id")
        public _FinalStage quotePriceId(@NotNull String quotePriceId) {
            this.quotePriceId = Objects.requireNonNull(quotePriceId, "quotePriceId must not be null");
            return this;
        }

        /**
         * <p>Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage extraFields(Map<String, Object> extraFields) {
            this.extraFields = Optional.ofNullable(extraFields);
            return this;
        }

        /**
         * <p>Optional free-form object with additional fields. Total JSON-encoded size must not exceed 255 characters.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "extra_fields", nulls = Nulls.SKIP)
        public _FinalStage extraFields(Optional<Map<String, Object>> extraFields) {
            this.extraFields = extraFields;
            return this;
        }

        /**
         * <p>List of benefit UUIDs</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage benefits(List<String> benefits) {
            this.benefits = Optional.ofNullable(benefits);
            return this;
        }

        /**
         * <p>List of benefit UUIDs</p>
         */
        @java.lang.Override
        @JsonSetter(value = "benefits", nulls = Nulls.SKIP)
        public _FinalStage benefits(Optional<List<String>> benefits) {
            this.benefits = benefits;
            return this;
        }

        @java.lang.Override
        public PostPoliciesRequest build() {
            return new PostPoliciesRequest(
                    otp, quoteRequestId, quoteReferenceId, quotePriceId, benefits, extraFields, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
