/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.errors;

import com.yasminaai.api.core.YasminaaiApiApiException;
import java.util.Map;
import okhttp3.Response;

public final class UnprocessableEntityError extends YasminaaiApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final Map<String, Object> body;

    public UnprocessableEntityError(Map<String, Object> body) {
        super("UnprocessableEntityError", 422, body);
        this.body = body;
    }

    public UnprocessableEntityError(Map<String, Object> body, Response rawResponse) {
        super("UnprocessableEntityError", 422, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public Map<String, Object> body() {
        return this.body;
    }
}
