/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.otps;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.otps.requests.PostIssueOtpRequest;
import com.yasminaai.api.resources.otps.requests.PostQuoteOtpRequest;
import java.util.concurrent.CompletableFuture;

public class AsyncOtPsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawOtPsClient rawClient;

    public AsyncOtPsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawOtPsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawOtPsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
     */
    public CompletableFuture<Void> requestOtpForQuoteVerification(PostQuoteOtpRequest request) {
        return this.rawClient.requestOtpForQuoteVerification(request).thenApply(response -> response.body());
    }

    /**
     * This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
     */
    public CompletableFuture<Void> requestOtpForQuoteVerification(
            PostQuoteOtpRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .requestOtpForQuoteVerification(request, requestOptions)
                .thenApply(response -> response.body());
    }

    /**
     * This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
     */
    public CompletableFuture<Void> requestOtpForIssuingPolicy(PostIssueOtpRequest request) {
        return this.rawClient.requestOtpForIssuingPolicy(request).thenApply(response -> response.body());
    }

    /**
     * This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
     */
    public CompletableFuture<Void> requestOtpForIssuingPolicy(
            PostIssueOtpRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .requestOtpForIssuingPolicy(request, requestOptions)
                .thenApply(response -> response.body());
    }
}
