/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.otps;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.otps.requests.PostIssueOtpRequest;
import com.yasminaai.api.resources.otps.requests.PostQuoteOtpRequest;

public class OtPsClient {
    protected final ClientOptions clientOptions;

    private final RawOtPsClient rawClient;

    public OtPsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawOtPsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawOtPsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
     */
    public void requestOtpForQuoteVerification(PostQuoteOtpRequest request) {
        this.rawClient.requestOtpForQuoteVerification(request).body();
    }

    /**
     * This endpoint sends a one-time password (OTP) to the provided email and phone number for quote verification. It should be called before creating a quote request.
     */
    public void requestOtpForQuoteVerification(PostQuoteOtpRequest request, RequestOptions requestOptions) {
        this.rawClient.requestOtpForQuoteVerification(request, requestOptions).body();
    }

    /**
     * This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
     */
    public void requestOtpForIssuingPolicy(PostIssueOtpRequest request) {
        this.rawClient.requestOtpForIssuingPolicy(request).body();
    }

    /**
     * This endpoint sends a one-time password (OTP). It should be called before issuing a policy.
     */
    public void requestOtpForIssuingPolicy(PostIssueOtpRequest request, RequestOptions requestOptions) {
        this.rawClient.requestOtpForIssuingPolicy(request, requestOptions).body();
    }
}
