/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.Suppliers;
import com.yasminaai.api.resources.otps.AsyncOtPsClient;
import com.yasminaai.api.resources.policies.AsyncPoliciesClient;
import com.yasminaai.api.resources.quotes.AsyncQuotesClient;
import java.util.function.Supplier;

public class AsyncYasminaaiApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncQuotesClient> quotesClient;

    protected final Supplier<AsyncPoliciesClient> policiesClient;

    protected final Supplier<AsyncOtPsClient> otPsClient;

    public AsyncYasminaaiApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.quotesClient = Suppliers.memoize(() -> new AsyncQuotesClient(clientOptions));
        this.policiesClient = Suppliers.memoize(() -> new AsyncPoliciesClient(clientOptions));
        this.otPsClient = Suppliers.memoize(() -> new AsyncOtPsClient(clientOptions));
    }

    public AsyncQuotesClient quotes() {
        return this.quotesClient.get();
    }

    public AsyncPoliciesClient policies() {
        return this.policiesClient.get();
    }

    public AsyncOtPsClient otPs() {
        return this.otPsClient.get();
    }

    public static AsyncYasminaaiApiClientBuilder builder() {
        return new AsyncYasminaaiApiClientBuilder();
    }
}
