/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.Suppliers;
import com.yasminaai.api.resources.otps.OtPsClient;
import com.yasminaai.api.resources.policies.PoliciesClient;
import com.yasminaai.api.resources.quotes.QuotesClient;
import java.util.function.Supplier;

public class YasminaaiApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<QuotesClient> quotesClient;

    protected final Supplier<PoliciesClient> policiesClient;

    protected final Supplier<OtPsClient> otPsClient;

    public YasminaaiApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.quotesClient = Suppliers.memoize(() -> new QuotesClient(clientOptions));
        this.policiesClient = Suppliers.memoize(() -> new PoliciesClient(clientOptions));
        this.otPsClient = Suppliers.memoize(() -> new OtPsClient(clientOptions));
    }

    public QuotesClient quotes() {
        return this.quotesClient.get();
    }

    public PoliciesClient policies() {
        return this.policiesClient.get();
    }

    public OtPsClient otPs() {
        return this.otPsClient.get();
    }

    public static YasminaaiApiClientBuilder builder() {
        return new YasminaaiApiClientBuilder();
    }
}
