/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.quotes.requests.DeleteQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.GetQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.GetQuoteRequestsRequest;
import com.yasminaai.api.resources.quotes.requests.PostQuoteRequestsRequest;
import com.yasminaai.api.resources.quotes.types.DeleteQuoteRequestsIdResponse;
import com.yasminaai.api.types.PaginatedQuoteResponse;
import com.yasminaai.api.types.QuoteResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncQuotesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawQuotesClient rawClient;

    public AsyncQuotesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawQuotesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawQuotesClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<QuoteResponse> showQuote(int id) {
        return this.rawClient.showQuote(id).thenApply(response -> response.body());
    }

    public CompletableFuture<QuoteResponse> showQuote(int id, RequestOptions requestOptions) {
        return this.rawClient.showQuote(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<QuoteResponse> showQuote(int id, GetQuoteRequestsIdRequest request) {
        return this.rawClient.showQuote(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<QuoteResponse> showQuote(
            int id, GetQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.showQuote(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteQuoteRequestsIdResponse> deleteQuote(int id) {
        return this.rawClient.deleteQuote(id).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteQuoteRequestsIdResponse> deleteQuote(int id, RequestOptions requestOptions) {
        return this.rawClient.deleteQuote(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteQuoteRequestsIdResponse> deleteQuote(int id, DeleteQuoteRequestsIdRequest request) {
        return this.rawClient.deleteQuote(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<DeleteQuoteRequestsIdResponse> deleteQuote(
            int id, DeleteQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteQuote(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PaginatedQuoteResponse> listQuotes() {
        return this.rawClient.listQuotes().thenApply(response -> response.body());
    }

    public CompletableFuture<PaginatedQuoteResponse> listQuotes(RequestOptions requestOptions) {
        return this.rawClient.listQuotes(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<PaginatedQuoteResponse> listQuotes(GetQuoteRequestsRequest request) {
        return this.rawClient.listQuotes(request).thenApply(response -> response.body());
    }

    public CompletableFuture<PaginatedQuoteResponse> listQuotes(
            GetQuoteRequestsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listQuotes(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public CompletableFuture<QuoteResponse> requestQuotes(PostQuoteRequestsRequest request) {
        return this.rawClient.requestQuotes(request).thenApply(response -> response.body());
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public CompletableFuture<QuoteResponse> requestQuotes(
            PostQuoteRequestsRequest request, RequestOptions requestOptions) {
        return this.rawClient.requestQuotes(request, requestOptions).thenApply(response -> response.body());
    }
}
