/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.MediaTypes;
import com.yasminaai.api.core.ObjectMappers;
import com.yasminaai.api.core.QueryStringMapper;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.core.YasminaaiApiApiException;
import com.yasminaai.api.core.YasminaaiApiException;
import com.yasminaai.api.core.YasminaaiApiHttpResponse;
import com.yasminaai.api.errors.NotFoundError;
import com.yasminaai.api.errors.UnauthorizedError;
import com.yasminaai.api.resources.quotes.requests.DeleteQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.GetQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.GetQuoteRequestsRequest;
import com.yasminaai.api.resources.quotes.requests.PostQuoteRequestsRequest;
import com.yasminaai.api.resources.quotes.types.DeleteQuoteRequestsIdResponse;
import com.yasminaai.api.types.PaginatedQuoteResponse;
import com.yasminaai.api.types.QuoteResponse;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawQuotesClient {
    protected final ClientOptions clientOptions;

    public AsyncRawQuotesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> showQuote(int id) {
        return showQuote(id, GetQuoteRequestsIdRequest.builder().build());
    }

    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> showQuote(int id, RequestOptions requestOptions) {
        return showQuote(id, GetQuoteRequestsIdRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> showQuote(
            int id, GetQuoteRequestsIdRequest request) {
        return showQuote(id, request, null);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> showQuote(
            int id, GetQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("quote-requests")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new YasminaaiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, QuoteResponse.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 404) {
                            future.completeExceptionally(new NotFoundError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new YasminaaiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<YasminaaiApiHttpResponse<DeleteQuoteRequestsIdResponse>> deleteQuote(int id) {
        return deleteQuote(id, DeleteQuoteRequestsIdRequest.builder().build());
    }

    public CompletableFuture<YasminaaiApiHttpResponse<DeleteQuoteRequestsIdResponse>> deleteQuote(
            int id, RequestOptions requestOptions) {
        return deleteQuote(id, DeleteQuoteRequestsIdRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<DeleteQuoteRequestsIdResponse>> deleteQuote(
            int id, DeleteQuoteRequestsIdRequest request) {
        return deleteQuote(id, request, null);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<DeleteQuoteRequestsIdResponse>> deleteQuote(
            int id, DeleteQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("quote-requests")
                .addPathSegment(Integer.toString(id));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<YasminaaiApiHttpResponse<DeleteQuoteRequestsIdResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new YasminaaiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, DeleteQuoteRequestsIdResponse.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 404) {
                            future.completeExceptionally(new NotFoundError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new YasminaaiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<YasminaaiApiHttpResponse<PaginatedQuoteResponse>> listQuotes() {
        return listQuotes(GetQuoteRequestsRequest.builder().build());
    }

    public CompletableFuture<YasminaaiApiHttpResponse<PaginatedQuoteResponse>> listQuotes(
            RequestOptions requestOptions) {
        return listQuotes(GetQuoteRequestsRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<PaginatedQuoteResponse>> listQuotes(
            GetQuoteRequestsRequest request) {
        return listQuotes(request, null);
    }

    public CompletableFuture<YasminaaiApiHttpResponse<PaginatedQuoteResponse>> listQuotes(
            GetQuoteRequestsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("quote-requests");
        if (request.getDateFrom().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "date_from", request.getDateFrom().get(), false);
        }
        if (request.getDateTo().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "date_to", request.getDateTo().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (request.getIncludeAggregates().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "include_aggregates",
                    request.getIncludeAggregates().get(),
                    false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<YasminaaiApiHttpResponse<PaginatedQuoteResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new YasminaaiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PaginatedQuoteResponse.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 401) {
                            future.completeExceptionally(new UnauthorizedError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new YasminaaiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> requestQuotes(PostQuoteRequestsRequest request) {
        return requestQuotes(request, null);
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> requestQuotes(
            PostQuoteRequestsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("quote-requests");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        if (request.getAcceptLanguage().isPresent()) {
            _requestBuilder.addHeader(
                    "Accept-Language", request.getAcceptLanguage().get().toString());
        }
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<YasminaaiApiHttpResponse<QuoteResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new YasminaaiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, QuoteResponse.class),
                                response));
                        return;
                    }
                    try {
                        if (response.code() == 401) {
                            future.completeExceptionally(new UnauthorizedError(
                                    ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
                            return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new YasminaaiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new YasminaaiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
