/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.quotes.requests.DeleteQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.GetQuoteRequestsIdRequest;
import com.yasminaai.api.resources.quotes.requests.PostQuoteRequestsRequest;
import com.yasminaai.api.resources.quotes.types.DeleteQuoteRequestsIdResponse;
import com.yasminaai.api.resources.quotes.types.GetQuoteRequestsResponse;
import com.yasminaai.api.types.QuoteResponse;

public class QuotesClient {
    protected final ClientOptions clientOptions;

    private final RawQuotesClient rawClient;

    public QuotesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawQuotesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawQuotesClient withRawResponse() {
        return this.rawClient;
    }

    public QuoteResponse showQuote(int id) {
        return this.rawClient.showQuote(id).body();
    }

    public QuoteResponse showQuote(int id, RequestOptions requestOptions) {
        return this.rawClient.showQuote(id, requestOptions).body();
    }

    public QuoteResponse showQuote(int id, GetQuoteRequestsIdRequest request) {
        return this.rawClient.showQuote(id, request).body();
    }

    public QuoteResponse showQuote(int id, GetQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.showQuote(id, request, requestOptions).body();
    }

    public DeleteQuoteRequestsIdResponse deleteQuote(int id) {
        return this.rawClient.deleteQuote(id).body();
    }

    public DeleteQuoteRequestsIdResponse deleteQuote(int id, RequestOptions requestOptions) {
        return this.rawClient.deleteQuote(id, requestOptions).body();
    }

    public DeleteQuoteRequestsIdResponse deleteQuote(int id, DeleteQuoteRequestsIdRequest request) {
        return this.rawClient.deleteQuote(id, request).body();
    }

    public DeleteQuoteRequestsIdResponse deleteQuote(
            int id, DeleteQuoteRequestsIdRequest request, RequestOptions requestOptions) {
        return this.rawClient.deleteQuote(id, request, requestOptions).body();
    }

    public GetQuoteRequestsResponse listQuotes() {
        return this.rawClient.listQuotes().body();
    }

    public GetQuoteRequestsResponse listQuotes(RequestOptions requestOptions) {
        return this.rawClient.listQuotes(requestOptions).body();
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public QuoteResponse requestQuotes(PostQuoteRequestsRequest request) {
        return this.rawClient.requestQuotes(request).body();
    }

    /**
     * For getting prices with benefits.
     * The Quote IDs can be used later to issue a policy
     */
    public QuoteResponse requestQuotes(PostQuoteRequestsRequest request, RequestOptions requestOptions) {
        return this.rawClient.requestQuotes(request, requestOptions).body();
    }
}
