/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.policies;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.policies.requests.GetPoliciesCarPolicyRequest;
import com.yasminaai.api.resources.policies.requests.GetPoliciesRequest;
import com.yasminaai.api.resources.policies.requests.PostPoliciesRequest;
import com.yasminaai.api.types.PaginatedPolicyResponse;
import com.yasminaai.api.types.Policy;
import java.util.concurrent.CompletableFuture;

public class AsyncPoliciesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPoliciesClient rawClient;

    public AsyncPoliciesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPoliciesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPoliciesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Show a specific policy
     */
    public CompletableFuture<Policy> showPolicy(int carPolicy) {
        return this.rawClient.showPolicy(carPolicy).thenApply(response -> response.body());
    }

    /**
     * Show a specific policy
     */
    public CompletableFuture<Policy> showPolicy(int carPolicy, RequestOptions requestOptions) {
        return this.rawClient.showPolicy(carPolicy, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Show a specific policy
     */
    public CompletableFuture<Policy> showPolicy(int carPolicy, GetPoliciesCarPolicyRequest request) {
        return this.rawClient.showPolicy(carPolicy, request).thenApply(response -> response.body());
    }

    /**
     * Show a specific policy
     */
    public CompletableFuture<Policy> showPolicy(
            int carPolicy, GetPoliciesCarPolicyRequest request, RequestOptions requestOptions) {
        return this.rawClient.showPolicy(carPolicy, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Listing requested policies
     */
    public CompletableFuture<PaginatedPolicyResponse> listPolicies() {
        return this.rawClient.listPolicies().thenApply(response -> response.body());
    }

    /**
     * Listing requested policies
     */
    public CompletableFuture<PaginatedPolicyResponse> listPolicies(RequestOptions requestOptions) {
        return this.rawClient.listPolicies(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Listing requested policies
     */
    public CompletableFuture<PaginatedPolicyResponse> listPolicies(GetPoliciesRequest request) {
        return this.rawClient.listPolicies(request).thenApply(response -> response.body());
    }

    /**
     * Listing requested policies
     */
    public CompletableFuture<PaginatedPolicyResponse> listPolicies(
            GetPoliciesRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPolicies(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * For issuing a new policy
     */
    public CompletableFuture<Policy> issuePolicy(PostPoliciesRequest request) {
        return this.rawClient.issuePolicy(request).thenApply(response -> response.body());
    }

    /**
     * For issuing a new policy
     */
    public CompletableFuture<Policy> issuePolicy(PostPoliciesRequest request, RequestOptions requestOptions) {
        return this.rawClient.issuePolicy(request, requestOptions).thenApply(response -> response.body());
    }
}
