/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.policies;

import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.resources.policies.requests.GetPoliciesCarPolicyRequest;
import com.yasminaai.api.resources.policies.requests.GetPoliciesRequest;
import com.yasminaai.api.resources.policies.requests.PostPoliciesRequest;
import com.yasminaai.api.types.PaginatedPolicyResponse;
import com.yasminaai.api.types.Policy;

public class PoliciesClient {
    protected final ClientOptions clientOptions;

    private final RawPoliciesClient rawClient;

    public PoliciesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPoliciesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPoliciesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Show a specific policy
     */
    public Policy showPolicy(int carPolicy) {
        return this.rawClient.showPolicy(carPolicy).body();
    }

    /**
     * Show a specific policy
     */
    public Policy showPolicy(int carPolicy, RequestOptions requestOptions) {
        return this.rawClient.showPolicy(carPolicy, requestOptions).body();
    }

    /**
     * Show a specific policy
     */
    public Policy showPolicy(int carPolicy, GetPoliciesCarPolicyRequest request) {
        return this.rawClient.showPolicy(carPolicy, request).body();
    }

    /**
     * Show a specific policy
     */
    public Policy showPolicy(int carPolicy, GetPoliciesCarPolicyRequest request, RequestOptions requestOptions) {
        return this.rawClient.showPolicy(carPolicy, request, requestOptions).body();
    }

    /**
     * Listing requested policies
     */
    public PaginatedPolicyResponse listPolicies() {
        return this.rawClient.listPolicies().body();
    }

    /**
     * Listing requested policies
     */
    public PaginatedPolicyResponse listPolicies(RequestOptions requestOptions) {
        return this.rawClient.listPolicies(requestOptions).body();
    }

    /**
     * Listing requested policies
     */
    public PaginatedPolicyResponse listPolicies(GetPoliciesRequest request) {
        return this.rawClient.listPolicies(request).body();
    }

    /**
     * Listing requested policies
     */
    public PaginatedPolicyResponse listPolicies(GetPoliciesRequest request, RequestOptions requestOptions) {
        return this.rawClient.listPolicies(request, requestOptions).body();
    }

    /**
     * For issuing a new policy
     */
    public Policy issuePolicy(PostPoliciesRequest request) {
        return this.rawClient.issuePolicy(request).body();
    }

    /**
     * For issuing a new policy
     */
    public Policy issuePolicy(PostPoliciesRequest request, RequestOptions requestOptions) {
        return this.rawClient.issuePolicy(request, requestOptions).body();
    }
}
