/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.policies;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.yasminaai.api.core.ClientOptions;
import com.yasminaai.api.core.MediaTypes;
import com.yasminaai.api.core.ObjectMappers;
import com.yasminaai.api.core.QueryStringMapper;
import com.yasminaai.api.core.RequestOptions;
import com.yasminaai.api.core.YasminaaiApiApiException;
import com.yasminaai.api.core.YasminaaiApiException;
import com.yasminaai.api.core.YasminaaiApiHttpResponse;
import com.yasminaai.api.errors.UnauthorizedError;
import com.yasminaai.api.errors.UnprocessableEntityError;
import com.yasminaai.api.resources.policies.requests.GetPoliciesCarPolicyRequest;
import com.yasminaai.api.resources.policies.requests.GetPoliciesRequest;
import com.yasminaai.api.resources.policies.requests.PostPoliciesRequest;
import com.yasminaai.api.types.Policy;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawPoliciesClient {
    protected final ClientOptions clientOptions;

    public RawPoliciesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Show a specific policy
     */
    public YasminaaiApiHttpResponse<Policy> showPolicy(int carPolicy) {
        return showPolicy(carPolicy, GetPoliciesCarPolicyRequest.builder().build());
    }

    /**
     * Show a specific policy
     */
    public YasminaaiApiHttpResponse<Policy> showPolicy(int carPolicy, RequestOptions requestOptions) {
        return showPolicy(carPolicy, GetPoliciesCarPolicyRequest.builder().build(), requestOptions);
    }

    /**
     * Show a specific policy
     */
    public YasminaaiApiHttpResponse<Policy> showPolicy(int carPolicy, GetPoliciesCarPolicyRequest request) {
        return showPolicy(carPolicy, request, null);
    }

    /**
     * Show a specific policy
     */
    public YasminaaiApiHttpResponse<Policy> showPolicy(
            int carPolicy, GetPoliciesCarPolicyRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("policies")
                .addPathSegment(Integer.toString(carPolicy));
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new YasminaaiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Policy.class), response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new YasminaaiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new YasminaaiApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Listing requested policies
     */
    public YasminaaiApiHttpResponse<List<Policy>> listPolicies() {
        return listPolicies(GetPoliciesRequest.builder().build());
    }

    /**
     * Listing requested policies
     */
    public YasminaaiApiHttpResponse<List<Policy>> listPolicies(RequestOptions requestOptions) {
        return listPolicies(GetPoliciesRequest.builder().build(), requestOptions);
    }

    /**
     * Listing requested policies
     */
    public YasminaaiApiHttpResponse<List<Policy>> listPolicies(GetPoliciesRequest request) {
        return listPolicies(request, null);
    }

    /**
     * Listing requested policies
     */
    public YasminaaiApiHttpResponse<List<Policy>> listPolicies(
            GetPoliciesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("policies");
        if (request.getQuoteRequestId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "quote_request_id", request.getQuoteRequestId().get(), false);
        }
        if (request.getQuotePriceId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "quote_price_id", request.getQuotePriceId().get(), false);
        }
        if (request.getProviderPolicyId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "provider_policy_id", request.getProviderPolicyId().get(), false);
        }
        if (request.getCarSequenceNumber().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "car_sequence_number",
                    request.getCarSequenceNumber().get(),
                    false);
        }
        if (request.getNewOwnerId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "new_owner_id", request.getNewOwnerId().get(), false);
        }
        if (request.getPreviousOwnerId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "previous_owner_id", request.getPreviousOwnerId().get(), false);
        }
        if (request.getStatus().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "status", request.getStatus().get(), false);
        }
        if (request.getMinPrice().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_price", request.getMinPrice().get(), false);
        }
        if (request.getMaxPrice().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_price", request.getMaxPrice().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new YasminaaiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, new TypeReference<List<Policy>>() {}),
                        response);
            }
            try {
                if (response.code() == 401) {
                    throw new UnauthorizedError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new YasminaaiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new YasminaaiApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * For issuing a new policy
     */
    public YasminaaiApiHttpResponse<Policy> issuePolicy(PostPoliciesRequest request) {
        return issuePolicy(request, null);
    }

    /**
     * For issuing a new policy
     */
    public YasminaaiApiHttpResponse<Policy> issuePolicy(PostPoliciesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("policies");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new YasminaaiApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new YasminaaiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Policy.class), response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, new TypeReference<Map<String, Object>>() {}),
                                response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new YasminaaiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new YasminaaiApiException("Network error executing HTTP request", e);
        }
    }
}
