/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.core;

public final class Environment {
    public static final Environment SANDBOX = new Environment("https://sandbox.yasmina.ai/api/v1/car-comp");

    public static final Environment PRODUCTION = new Environment("https://production.yasmina.ai/api/v1/car-comp");

    private final String url;

    private Environment(String url) {
        this.url = url;
    }

    public String getUrl() {
        return this.url;
    }

    public static Environment custom(String url) {
        return new Environment(url);
    }
}
