/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class YasminaaiApiException extends RuntimeException {
    public YasminaaiApiException(String message) {
        super(message);
    }

    public YasminaaiApiException(String message, Exception e) {
        super(message, e);
    }
}
