/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class PostQuoteRequestsRequestAcceptLanguage {
    public static final PostQuoteRequestsRequestAcceptLanguage AR =
            new PostQuoteRequestsRequestAcceptLanguage(Value.AR, "ar");

    private final Value value;

    private final String string;

    PostQuoteRequestsRequestAcceptLanguage(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof PostQuoteRequestsRequestAcceptLanguage
                        && this.string.equals(((PostQuoteRequestsRequestAcceptLanguage) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case AR:
                return visitor.visitAr();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static PostQuoteRequestsRequestAcceptLanguage valueOf(String value) {
        switch (value) {
            case "ar":
                return AR;
            default:
                return new PostQuoteRequestsRequestAcceptLanguage(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAr();

        T visitUnknown(String unknownType);
    }
}
