/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.resources.quotes.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PostQuoteRequestsRequestDriversItem.Builder.class)
public final class PostQuoteRequestsRequestDriversItem {
    private final String ownerId;

    private final String birthdate;

    private final int drivingPercentage;

    private final Map<String, Object> additionalProperties;

    private PostQuoteRequestsRequestDriversItem(
            String ownerId, String birthdate, int drivingPercentage, Map<String, Object> additionalProperties) {
        this.ownerId = ownerId;
        this.birthdate = birthdate;
        this.drivingPercentage = drivingPercentage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Driver's national ID. Must be 10 digits starting with 1, 2, or 7.
     */
    @JsonProperty("owner_id")
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * @return Driver's birthdate in YYYY-MM-DD format.
     */
    @JsonProperty("birthdate")
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * @return Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.
     */
    @JsonProperty("driving_percentage")
    public int getDrivingPercentage() {
        return drivingPercentage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PostQuoteRequestsRequestDriversItem
                && equalTo((PostQuoteRequestsRequestDriversItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PostQuoteRequestsRequestDriversItem other) {
        return ownerId.equals(other.ownerId)
                && birthdate.equals(other.birthdate)
                && drivingPercentage == other.drivingPercentage;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.ownerId, this.birthdate, this.drivingPercentage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OwnerIdStage builder() {
        return new Builder();
    }

    public interface OwnerIdStage {
        /**
         * <p>Driver's national ID. Must be 10 digits starting with 1, 2, or 7.</p>
         */
        BirthdateStage ownerId(@NotNull String ownerId);

        Builder from(PostQuoteRequestsRequestDriversItem other);
    }

    public interface BirthdateStage {
        /**
         * <p>Driver's birthdate in YYYY-MM-DD format.</p>
         */
        DrivingPercentageStage birthdate(@NotNull String birthdate);
    }

    public interface DrivingPercentageStage {
        /**
         * <p>Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.</p>
         */
        _FinalStage drivingPercentage(int drivingPercentage);
    }

    public interface _FinalStage {
        PostQuoteRequestsRequestDriversItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OwnerIdStage, BirthdateStage, DrivingPercentageStage, _FinalStage {
        private String ownerId;

        private String birthdate;

        private int drivingPercentage;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(PostQuoteRequestsRequestDriversItem other) {
            ownerId(other.getOwnerId());
            birthdate(other.getBirthdate());
            drivingPercentage(other.getDrivingPercentage());
            return this;
        }

        /**
         * <p>Driver's national ID. Must be 10 digits starting with 1, 2, or 7.</p>
         * <p>Driver's national ID. Must be 10 digits starting with 1, 2, or 7.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("owner_id")
        public BirthdateStage ownerId(@NotNull String ownerId) {
            this.ownerId = Objects.requireNonNull(ownerId, "ownerId must not be null");
            return this;
        }

        /**
         * <p>Driver's birthdate in YYYY-MM-DD format.</p>
         * <p>Driver's birthdate in YYYY-MM-DD format.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("birthdate")
        public DrivingPercentageStage birthdate(@NotNull String birthdate) {
            this.birthdate = Objects.requireNonNull(birthdate, "birthdate must not be null");
            return this;
        }

        /**
         * <p>Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.</p>
         * <p>Percentage of driving for this driver. Valid values are 25, 50, 75, or 100. The sum of all drivers' percentages must equal 100.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("driving_percentage")
        public _FinalStage drivingPercentage(int drivingPercentage) {
            this.drivingPercentage = drivingPercentage;
            return this;
        }

        @java.lang.Override
        public PostQuoteRequestsRequestDriversItem build() {
            return new PostQuoteRequestsRequestDriversItem(ownerId, birthdate, drivingPercentage, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
