/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.Nullable;
import com.yasminaai.api.core.NullableNonemptyFilter;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Benefit.Builder.class)
public final class Benefit {
    private final Optional<String> quoteBenefitId;

    private final Optional<String> id;

    private final Optional<String> name;

    private final Optional<String> nameAr;

    private final Optional<Double> amount;

    private final Optional<Double> vat;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private Benefit(
            Optional<String> quoteBenefitId,
            Optional<String> id,
            Optional<String> name,
            Optional<String> nameAr,
            Optional<Double> amount,
            Optional<Double> vat,
            Optional<String> url,
            Map<String, Object> additionalProperties) {
        this.quoteBenefitId = quoteBenefitId;
        this.id = id;
        this.name = name;
        this.nameAr = nameAr;
        this.amount = amount;
        this.vat = vat;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("quote_benefit_id")
    public Optional<String> getQuoteBenefitId() {
        return quoteBenefitId;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Arabic name of the benefit. Use this field instead of <code>name</code> when rendering Arabic UIs.
     */
    @JsonProperty("name_ar")
    public Optional<String> getNameAr() {
        return nameAr;
    }

    @JsonProperty("amount")
    public Optional<Double> getAmount() {
        return amount;
    }

    @JsonProperty("vat")
    public Optional<Double> getVat() {
        return vat;
    }

    @JsonIgnore
    public Optional<String> getUrl() {
        if (url == null) {
            return Optional.empty();
        }
        return url;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("url")
    private Optional<String> _getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Benefit && equalTo((Benefit) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Benefit other) {
        return quoteBenefitId.equals(other.quoteBenefitId)
                && id.equals(other.id)
                && name.equals(other.name)
                && nameAr.equals(other.nameAr)
                && amount.equals(other.amount)
                && vat.equals(other.vat)
                && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.quoteBenefitId, this.id, this.name, this.nameAr, this.amount, this.vat, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> quoteBenefitId = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<String> nameAr = Optional.empty();

        private Optional<Double> amount = Optional.empty();

        private Optional<Double> vat = Optional.empty();

        private Optional<String> url = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Benefit other) {
            quoteBenefitId(other.getQuoteBenefitId());
            id(other.getId());
            name(other.getName());
            nameAr(other.getNameAr());
            amount(other.getAmount());
            vat(other.getVat());
            url(other.getUrl());
            return this;
        }

        @JsonSetter(value = "quote_benefit_id", nulls = Nulls.SKIP)
        public Builder quoteBenefitId(Optional<String> quoteBenefitId) {
            this.quoteBenefitId = quoteBenefitId;
            return this;
        }

        public Builder quoteBenefitId(String quoteBenefitId) {
            this.quoteBenefitId = Optional.ofNullable(quoteBenefitId);
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Arabic name of the benefit. Use this field instead of <code>name</code> when rendering Arabic UIs.</p>
         */
        @JsonSetter(value = "name_ar", nulls = Nulls.SKIP)
        public Builder nameAr(Optional<String> nameAr) {
            this.nameAr = nameAr;
            return this;
        }

        public Builder nameAr(String nameAr) {
            this.nameAr = Optional.ofNullable(nameAr);
            return this;
        }

        @JsonSetter(value = "amount", nulls = Nulls.SKIP)
        public Builder amount(Optional<Double> amount) {
            this.amount = amount;
            return this;
        }

        public Builder amount(Double amount) {
            this.amount = Optional.ofNullable(amount);
            return this;
        }

        @JsonSetter(value = "vat", nulls = Nulls.SKIP)
        public Builder vat(Optional<Double> vat) {
            this.vat = vat;
            return this;
        }

        public Builder vat(Double vat) {
            this.vat = Optional.ofNullable(vat);
            return this;
        }

        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public Builder url(Optional<String> url) {
            this.url = url;
            return this;
        }

        public Builder url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        public Builder url(Nullable<String> url) {
            if (url.isNull()) {
                this.url = null;
            } else if (url.isEmpty()) {
                this.url = Optional.empty();
            } else {
                this.url = Optional.of(url.get());
            }
            return this;
        }

        public Benefit build() {
            return new Benefit(quoteBenefitId, id, name, nameAr, amount, vat, url, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
