/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CompanyQuote.Builder.class)
public final class CompanyQuote {
    private final Optional<String> companyName;

    private final Optional<String> companyNameAr;

    private final Optional<CompanyQuoteType> type;

    private final Optional<String> insuranceTypeDisplay;

    private final Optional<String> insuranceTypeDisplayAr;

    private final Optional<String> companyLogoUrl;

    private final Optional<String> squareCompanyLogoUrl;

    private final Optional<List<QuotePrice>> prices;

    private final Optional<List<Benefit>> benefits;

    private final Map<String, Object> additionalProperties;

    private CompanyQuote(
            Optional<String> companyName,
            Optional<String> companyNameAr,
            Optional<CompanyQuoteType> type,
            Optional<String> insuranceTypeDisplay,
            Optional<String> insuranceTypeDisplayAr,
            Optional<String> companyLogoUrl,
            Optional<String> squareCompanyLogoUrl,
            Optional<List<QuotePrice>> prices,
            Optional<List<Benefit>> benefits,
            Map<String, Object> additionalProperties) {
        this.companyName = companyName;
        this.companyNameAr = companyNameAr;
        this.type = type;
        this.insuranceTypeDisplay = insuranceTypeDisplay;
        this.insuranceTypeDisplayAr = insuranceTypeDisplayAr;
        this.companyLogoUrl = companyLogoUrl;
        this.squareCompanyLogoUrl = squareCompanyLogoUrl;
        this.prices = prices;
        this.benefits = benefits;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("company_name")
    public Optional<String> getCompanyName() {
        return companyName;
    }

    /**
     * @return Arabic name of the insurance company. Use this field instead of <code>company_name</code> when rendering Arabic UIs.
     */
    @JsonProperty("company_name_ar")
    public Optional<String> getCompanyNameAr() {
        return companyNameAr;
    }

    /**
     * @return Normalised insurance category used to group and filter quotes. Always one of <code>TPL</code>, <code>TPL +</code>, or <code>Comprehensive</code>.
     */
    @JsonProperty("type")
    public Optional<CompanyQuoteType> getType() {
        return type;
    }

    /**
     * @return The insurance type label exactly as the insurance provider intends it to be displayed. While <code>type</code> normalises all non-TPL / non-Comprehensive values into <code>TPL +</code>, this field preserves the original provider string (e.g. &quot;TPL Plus&quot;, &quot;Third Party Plus&quot;) and should be shown in the UI wherever the provider's own wording is preferred.
     */
    @JsonProperty("insurance_type_display")
    public Optional<String> getInsuranceTypeDisplay() {
        return insuranceTypeDisplay;
    }

    /**
     * @return Arabic translation of <code>insurance_type_display</code>. Use this field for Arabic UIs. Falls back to the English value for provider-specific types that do not have a translation.
     */
    @JsonProperty("insurance_type_display_ar")
    public Optional<String> getInsuranceTypeDisplayAr() {
        return insuranceTypeDisplayAr;
    }

    /**
     * @return CDN URL for the insurance company's logo.
     */
    @JsonProperty("company_logo_url")
    public Optional<String> getCompanyLogoUrl() {
        return companyLogoUrl;
    }

    /**
     * @return CDN URL for the insurance company's square logo.
     */
    @JsonProperty("square_company_logo_url")
    public Optional<String> getSquareCompanyLogoUrl() {
        return squareCompanyLogoUrl;
    }

    @JsonProperty("prices")
    public Optional<List<QuotePrice>> getPrices() {
        return prices;
    }

    @JsonProperty("benefits")
    public Optional<List<Benefit>> getBenefits() {
        return benefits;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CompanyQuote && equalTo((CompanyQuote) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CompanyQuote other) {
        return companyName.equals(other.companyName)
                && companyNameAr.equals(other.companyNameAr)
                && type.equals(other.type)
                && insuranceTypeDisplay.equals(other.insuranceTypeDisplay)
                && insuranceTypeDisplayAr.equals(other.insuranceTypeDisplayAr)
                && companyLogoUrl.equals(other.companyLogoUrl)
                && squareCompanyLogoUrl.equals(other.squareCompanyLogoUrl)
                && prices.equals(other.prices)
                && benefits.equals(other.benefits);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.companyName,
                this.companyNameAr,
                this.type,
                this.insuranceTypeDisplay,
                this.insuranceTypeDisplayAr,
                this.companyLogoUrl,
                this.squareCompanyLogoUrl,
                this.prices,
                this.benefits);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyName = Optional.empty();

        private Optional<String> companyNameAr = Optional.empty();

        private Optional<CompanyQuoteType> type = Optional.empty();

        private Optional<String> insuranceTypeDisplay = Optional.empty();

        private Optional<String> insuranceTypeDisplayAr = Optional.empty();

        private Optional<String> companyLogoUrl = Optional.empty();

        private Optional<String> squareCompanyLogoUrl = Optional.empty();

        private Optional<List<QuotePrice>> prices = Optional.empty();

        private Optional<List<Benefit>> benefits = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CompanyQuote other) {
            companyName(other.getCompanyName());
            companyNameAr(other.getCompanyNameAr());
            type(other.getType());
            insuranceTypeDisplay(other.getInsuranceTypeDisplay());
            insuranceTypeDisplayAr(other.getInsuranceTypeDisplayAr());
            companyLogoUrl(other.getCompanyLogoUrl());
            squareCompanyLogoUrl(other.getSquareCompanyLogoUrl());
            prices(other.getPrices());
            benefits(other.getBenefits());
            return this;
        }

        @JsonSetter(value = "company_name", nulls = Nulls.SKIP)
        public Builder companyName(Optional<String> companyName) {
            this.companyName = companyName;
            return this;
        }

        public Builder companyName(String companyName) {
            this.companyName = Optional.ofNullable(companyName);
            return this;
        }

        /**
         * <p>Arabic name of the insurance company. Use this field instead of <code>company_name</code> when rendering Arabic UIs.</p>
         */
        @JsonSetter(value = "company_name_ar", nulls = Nulls.SKIP)
        public Builder companyNameAr(Optional<String> companyNameAr) {
            this.companyNameAr = companyNameAr;
            return this;
        }

        public Builder companyNameAr(String companyNameAr) {
            this.companyNameAr = Optional.ofNullable(companyNameAr);
            return this;
        }

        /**
         * <p>Normalised insurance category used to group and filter quotes. Always one of <code>TPL</code>, <code>TPL +</code>, or <code>Comprehensive</code>.</p>
         */
        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<CompanyQuoteType> type) {
            this.type = type;
            return this;
        }

        public Builder type(CompanyQuoteType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        /**
         * <p>The insurance type label exactly as the insurance provider intends it to be displayed. While <code>type</code> normalises all non-TPL / non-Comprehensive values into <code>TPL +</code>, this field preserves the original provider string (e.g. &quot;TPL Plus&quot;, &quot;Third Party Plus&quot;) and should be shown in the UI wherever the provider's own wording is preferred.</p>
         */
        @JsonSetter(value = "insurance_type_display", nulls = Nulls.SKIP)
        public Builder insuranceTypeDisplay(Optional<String> insuranceTypeDisplay) {
            this.insuranceTypeDisplay = insuranceTypeDisplay;
            return this;
        }

        public Builder insuranceTypeDisplay(String insuranceTypeDisplay) {
            this.insuranceTypeDisplay = Optional.ofNullable(insuranceTypeDisplay);
            return this;
        }

        /**
         * <p>Arabic translation of <code>insurance_type_display</code>. Use this field for Arabic UIs. Falls back to the English value for provider-specific types that do not have a translation.</p>
         */
        @JsonSetter(value = "insurance_type_display_ar", nulls = Nulls.SKIP)
        public Builder insuranceTypeDisplayAr(Optional<String> insuranceTypeDisplayAr) {
            this.insuranceTypeDisplayAr = insuranceTypeDisplayAr;
            return this;
        }

        public Builder insuranceTypeDisplayAr(String insuranceTypeDisplayAr) {
            this.insuranceTypeDisplayAr = Optional.ofNullable(insuranceTypeDisplayAr);
            return this;
        }

        /**
         * <p>CDN URL for the insurance company's logo.</p>
         */
        @JsonSetter(value = "company_logo_url", nulls = Nulls.SKIP)
        public Builder companyLogoUrl(Optional<String> companyLogoUrl) {
            this.companyLogoUrl = companyLogoUrl;
            return this;
        }

        public Builder companyLogoUrl(String companyLogoUrl) {
            this.companyLogoUrl = Optional.ofNullable(companyLogoUrl);
            return this;
        }

        /**
         * <p>CDN URL for the insurance company's square logo.</p>
         */
        @JsonSetter(value = "square_company_logo_url", nulls = Nulls.SKIP)
        public Builder squareCompanyLogoUrl(Optional<String> squareCompanyLogoUrl) {
            this.squareCompanyLogoUrl = squareCompanyLogoUrl;
            return this;
        }

        public Builder squareCompanyLogoUrl(String squareCompanyLogoUrl) {
            this.squareCompanyLogoUrl = Optional.ofNullable(squareCompanyLogoUrl);
            return this;
        }

        @JsonSetter(value = "prices", nulls = Nulls.SKIP)
        public Builder prices(Optional<List<QuotePrice>> prices) {
            this.prices = prices;
            return this;
        }

        public Builder prices(List<QuotePrice> prices) {
            this.prices = Optional.ofNullable(prices);
            return this;
        }

        @JsonSetter(value = "benefits", nulls = Nulls.SKIP)
        public Builder benefits(Optional<List<Benefit>> benefits) {
            this.benefits = benefits;
            return this;
        }

        public Builder benefits(List<Benefit> benefits) {
            this.benefits = Optional.ofNullable(benefits);
            return this;
        }

        public CompanyQuote build() {
            return new CompanyQuote(
                    companyName,
                    companyNameAr,
                    type,
                    insuranceTypeDisplay,
                    insuranceTypeDisplayAr,
                    companyLogoUrl,
                    squareCompanyLogoUrl,
                    prices,
                    benefits,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
