/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.Nullable;
import com.yasminaai.api.core.NullableNonemptyFilter;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PaginatedPolicyResponse.Builder.class)
public final class PaginatedPolicyResponse {
    private final Optional<Integer> currentPage;

    private final Optional<List<Policy>> data;

    private final Optional<String> firstPageUrl;

    private final Optional<Integer> from;

    private final Optional<Integer> lastPage;

    private final Optional<String> lastPageUrl;

    private final Optional<List<PaginationLink>> links;

    private final Optional<String> nextPageUrl;

    private final Optional<String> path;

    private final Optional<Integer> perPage;

    private final Optional<String> prevPageUrl;

    private final Optional<Integer> to;

    private final Optional<Integer> total;

    private final Optional<PolicyAggregates> aggregates;

    private final Map<String, Object> additionalProperties;

    private PaginatedPolicyResponse(
            Optional<Integer> currentPage,
            Optional<List<Policy>> data,
            Optional<String> firstPageUrl,
            Optional<Integer> from,
            Optional<Integer> lastPage,
            Optional<String> lastPageUrl,
            Optional<List<PaginationLink>> links,
            Optional<String> nextPageUrl,
            Optional<String> path,
            Optional<Integer> perPage,
            Optional<String> prevPageUrl,
            Optional<Integer> to,
            Optional<Integer> total,
            Optional<PolicyAggregates> aggregates,
            Map<String, Object> additionalProperties) {
        this.currentPage = currentPage;
        this.data = data;
        this.firstPageUrl = firstPageUrl;
        this.from = from;
        this.lastPage = lastPage;
        this.lastPageUrl = lastPageUrl;
        this.links = links;
        this.nextPageUrl = nextPageUrl;
        this.path = path;
        this.perPage = perPage;
        this.prevPageUrl = prevPageUrl;
        this.to = to;
        this.total = total;
        this.aggregates = aggregates;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("current_page")
    public Optional<Integer> getCurrentPage() {
        return currentPage;
    }

    @JsonProperty("data")
    public Optional<List<Policy>> getData() {
        return data;
    }

    @JsonProperty("first_page_url")
    public Optional<String> getFirstPageUrl() {
        return firstPageUrl;
    }

    @JsonIgnore
    public Optional<Integer> getFrom() {
        if (from == null) {
            return Optional.empty();
        }
        return from;
    }

    @JsonProperty("last_page")
    public Optional<Integer> getLastPage() {
        return lastPage;
    }

    @JsonProperty("last_page_url")
    public Optional<String> getLastPageUrl() {
        return lastPageUrl;
    }

    @JsonProperty("links")
    public Optional<List<PaginationLink>> getLinks() {
        return links;
    }

    @JsonIgnore
    public Optional<String> getNextPageUrl() {
        if (nextPageUrl == null) {
            return Optional.empty();
        }
        return nextPageUrl;
    }

    @JsonProperty("path")
    public Optional<String> getPath() {
        return path;
    }

    @JsonProperty("per_page")
    public Optional<Integer> getPerPage() {
        return perPage;
    }

    @JsonIgnore
    public Optional<String> getPrevPageUrl() {
        if (prevPageUrl == null) {
            return Optional.empty();
        }
        return prevPageUrl;
    }

    @JsonIgnore
    public Optional<Integer> getTo() {
        if (to == null) {
            return Optional.empty();
        }
        return to;
    }

    @JsonProperty("total")
    public Optional<Integer> getTotal() {
        return total;
    }

    @JsonProperty("aggregates")
    public Optional<PolicyAggregates> getAggregates() {
        return aggregates;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("from")
    private Optional<Integer> _getFrom() {
        return from;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("next_page_url")
    private Optional<String> _getNextPageUrl() {
        return nextPageUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("prev_page_url")
    private Optional<String> _getPrevPageUrl() {
        return prevPageUrl;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("to")
    private Optional<Integer> _getTo() {
        return to;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PaginatedPolicyResponse && equalTo((PaginatedPolicyResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PaginatedPolicyResponse other) {
        return currentPage.equals(other.currentPage)
                && data.equals(other.data)
                && firstPageUrl.equals(other.firstPageUrl)
                && from.equals(other.from)
                && lastPage.equals(other.lastPage)
                && lastPageUrl.equals(other.lastPageUrl)
                && links.equals(other.links)
                && nextPageUrl.equals(other.nextPageUrl)
                && path.equals(other.path)
                && perPage.equals(other.perPage)
                && prevPageUrl.equals(other.prevPageUrl)
                && to.equals(other.to)
                && total.equals(other.total)
                && aggregates.equals(other.aggregates);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.currentPage,
                this.data,
                this.firstPageUrl,
                this.from,
                this.lastPage,
                this.lastPageUrl,
                this.links,
                this.nextPageUrl,
                this.path,
                this.perPage,
                this.prevPageUrl,
                this.to,
                this.total,
                this.aggregates);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> currentPage = Optional.empty();

        private Optional<List<Policy>> data = Optional.empty();

        private Optional<String> firstPageUrl = Optional.empty();

        private Optional<Integer> from = Optional.empty();

        private Optional<Integer> lastPage = Optional.empty();

        private Optional<String> lastPageUrl = Optional.empty();

        private Optional<List<PaginationLink>> links = Optional.empty();

        private Optional<String> nextPageUrl = Optional.empty();

        private Optional<String> path = Optional.empty();

        private Optional<Integer> perPage = Optional.empty();

        private Optional<String> prevPageUrl = Optional.empty();

        private Optional<Integer> to = Optional.empty();

        private Optional<Integer> total = Optional.empty();

        private Optional<PolicyAggregates> aggregates = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PaginatedPolicyResponse other) {
            currentPage(other.getCurrentPage());
            data(other.getData());
            firstPageUrl(other.getFirstPageUrl());
            from(other.getFrom());
            lastPage(other.getLastPage());
            lastPageUrl(other.getLastPageUrl());
            links(other.getLinks());
            nextPageUrl(other.getNextPageUrl());
            path(other.getPath());
            perPage(other.getPerPage());
            prevPageUrl(other.getPrevPageUrl());
            to(other.getTo());
            total(other.getTotal());
            aggregates(other.getAggregates());
            return this;
        }

        @JsonSetter(value = "current_page", nulls = Nulls.SKIP)
        public Builder currentPage(Optional<Integer> currentPage) {
            this.currentPage = currentPage;
            return this;
        }

        public Builder currentPage(Integer currentPage) {
            this.currentPage = Optional.ofNullable(currentPage);
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<List<Policy>> data) {
            this.data = data;
            return this;
        }

        public Builder data(List<Policy> data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        @JsonSetter(value = "first_page_url", nulls = Nulls.SKIP)
        public Builder firstPageUrl(Optional<String> firstPageUrl) {
            this.firstPageUrl = firstPageUrl;
            return this;
        }

        public Builder firstPageUrl(String firstPageUrl) {
            this.firstPageUrl = Optional.ofNullable(firstPageUrl);
            return this;
        }

        @JsonSetter(value = "from", nulls = Nulls.SKIP)
        public Builder from(Optional<Integer> from) {
            this.from = from;
            return this;
        }

        public Builder from(Integer from) {
            this.from = Optional.ofNullable(from);
            return this;
        }

        public Builder from(Nullable<Integer> from) {
            if (from.isNull()) {
                this.from = null;
            } else if (from.isEmpty()) {
                this.from = Optional.empty();
            } else {
                this.from = Optional.of(from.get());
            }
            return this;
        }

        @JsonSetter(value = "last_page", nulls = Nulls.SKIP)
        public Builder lastPage(Optional<Integer> lastPage) {
            this.lastPage = lastPage;
            return this;
        }

        public Builder lastPage(Integer lastPage) {
            this.lastPage = Optional.ofNullable(lastPage);
            return this;
        }

        @JsonSetter(value = "last_page_url", nulls = Nulls.SKIP)
        public Builder lastPageUrl(Optional<String> lastPageUrl) {
            this.lastPageUrl = lastPageUrl;
            return this;
        }

        public Builder lastPageUrl(String lastPageUrl) {
            this.lastPageUrl = Optional.ofNullable(lastPageUrl);
            return this;
        }

        @JsonSetter(value = "links", nulls = Nulls.SKIP)
        public Builder links(Optional<List<PaginationLink>> links) {
            this.links = links;
            return this;
        }

        public Builder links(List<PaginationLink> links) {
            this.links = Optional.ofNullable(links);
            return this;
        }

        @JsonSetter(value = "next_page_url", nulls = Nulls.SKIP)
        public Builder nextPageUrl(Optional<String> nextPageUrl) {
            this.nextPageUrl = nextPageUrl;
            return this;
        }

        public Builder nextPageUrl(String nextPageUrl) {
            this.nextPageUrl = Optional.ofNullable(nextPageUrl);
            return this;
        }

        public Builder nextPageUrl(Nullable<String> nextPageUrl) {
            if (nextPageUrl.isNull()) {
                this.nextPageUrl = null;
            } else if (nextPageUrl.isEmpty()) {
                this.nextPageUrl = Optional.empty();
            } else {
                this.nextPageUrl = Optional.of(nextPageUrl.get());
            }
            return this;
        }

        @JsonSetter(value = "path", nulls = Nulls.SKIP)
        public Builder path(Optional<String> path) {
            this.path = path;
            return this;
        }

        public Builder path(String path) {
            this.path = Optional.ofNullable(path);
            return this;
        }

        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(Optional<Integer> perPage) {
            this.perPage = perPage;
            return this;
        }

        public Builder perPage(Integer perPage) {
            this.perPage = Optional.ofNullable(perPage);
            return this;
        }

        @JsonSetter(value = "prev_page_url", nulls = Nulls.SKIP)
        public Builder prevPageUrl(Optional<String> prevPageUrl) {
            this.prevPageUrl = prevPageUrl;
            return this;
        }

        public Builder prevPageUrl(String prevPageUrl) {
            this.prevPageUrl = Optional.ofNullable(prevPageUrl);
            return this;
        }

        public Builder prevPageUrl(Nullable<String> prevPageUrl) {
            if (prevPageUrl.isNull()) {
                this.prevPageUrl = null;
            } else if (prevPageUrl.isEmpty()) {
                this.prevPageUrl = Optional.empty();
            } else {
                this.prevPageUrl = Optional.of(prevPageUrl.get());
            }
            return this;
        }

        @JsonSetter(value = "to", nulls = Nulls.SKIP)
        public Builder to(Optional<Integer> to) {
            this.to = to;
            return this;
        }

        public Builder to(Integer to) {
            this.to = Optional.ofNullable(to);
            return this;
        }

        public Builder to(Nullable<Integer> to) {
            if (to.isNull()) {
                this.to = null;
            } else if (to.isEmpty()) {
                this.to = Optional.empty();
            } else {
                this.to = Optional.of(to.get());
            }
            return this;
        }

        @JsonSetter(value = "total", nulls = Nulls.SKIP)
        public Builder total(Optional<Integer> total) {
            this.total = total;
            return this;
        }

        public Builder total(Integer total) {
            this.total = Optional.ofNullable(total);
            return this;
        }

        @JsonSetter(value = "aggregates", nulls = Nulls.SKIP)
        public Builder aggregates(Optional<PolicyAggregates> aggregates) {
            this.aggregates = aggregates;
            return this;
        }

        public Builder aggregates(PolicyAggregates aggregates) {
            this.aggregates = Optional.ofNullable(aggregates);
            return this;
        }

        public PaginatedPolicyResponse build() {
            return new PaginatedPolicyResponse(
                    currentPage,
                    data,
                    firstPageUrl,
                    from,
                    lastPage,
                    lastPageUrl,
                    links,
                    nextPageUrl,
                    path,
                    perPage,
                    prevPageUrl,
                    to,
                    total,
                    aggregates,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
