/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.Nullable;
import com.yasminaai.api.core.NullableNonemptyFilter;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = Policy.Builder.class)
public final class Policy {
    private final Optional<Integer> id;

    private final Optional<Map<String, Object>> metaData;

    private final Optional<String> startDate;

    private final Optional<Integer> providerPolicyId;

    private final Optional<String> providerPolicy;

    private final Optional<Integer> orderStatus;

    private final Optional<Integer> approvalStatus;

    private final Optional<String> endDate;

    private final Optional<Boolean> isClaimed;

    private final Optional<String> createdAt;

    private final Optional<String> updatedAt;

    private final Optional<String> clientId;

    private final Optional<String> canceledAt;

    private final Optional<String> invoice;

    private final Optional<String> cancellationDocument;

    private final Map<String, Object> additionalProperties;

    private Policy(
            Optional<Integer> id,
            Optional<Map<String, Object>> metaData,
            Optional<String> startDate,
            Optional<Integer> providerPolicyId,
            Optional<String> providerPolicy,
            Optional<Integer> orderStatus,
            Optional<Integer> approvalStatus,
            Optional<String> endDate,
            Optional<Boolean> isClaimed,
            Optional<String> createdAt,
            Optional<String> updatedAt,
            Optional<String> clientId,
            Optional<String> canceledAt,
            Optional<String> invoice,
            Optional<String> cancellationDocument,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.metaData = metaData;
        this.startDate = startDate;
        this.providerPolicyId = providerPolicyId;
        this.providerPolicy = providerPolicy;
        this.orderStatus = orderStatus;
        this.approvalStatus = approvalStatus;
        this.endDate = endDate;
        this.isClaimed = isClaimed;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.clientId = clientId;
        this.canceledAt = canceledAt;
        this.invoice = invoice;
        this.cancellationDocument = cancellationDocument;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<Integer> getId() {
        return id;
    }

    @JsonProperty("meta_data")
    public Optional<Map<String, Object>> getMetaData() {
        return metaData;
    }

    @JsonProperty("start_date")
    public Optional<String> getStartDate() {
        return startDate;
    }

    @JsonProperty("provider_policy_id")
    public Optional<Integer> getProviderPolicyId() {
        return providerPolicyId;
    }

    @JsonProperty("provider_policy")
    public Optional<String> getProviderPolicy() {
        return providerPolicy;
    }

    @JsonProperty("order_status")
    public Optional<Integer> getOrderStatus() {
        return orderStatus;
    }

    @JsonProperty("approval_status")
    public Optional<Integer> getApprovalStatus() {
        return approvalStatus;
    }

    @JsonProperty("end_date")
    public Optional<String> getEndDate() {
        return endDate;
    }

    @JsonProperty("is_claimed")
    public Optional<Boolean> getIsClaimed() {
        return isClaimed;
    }

    @JsonProperty("created_at")
    public Optional<String> getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("updated_at")
    public Optional<String> getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    @JsonIgnore
    public Optional<String> getCanceledAt() {
        if (canceledAt == null) {
            return Optional.empty();
        }
        return canceledAt;
    }

    @JsonProperty("invoice")
    public Optional<String> getInvoice() {
        return invoice;
    }

    @JsonProperty("cancellation_document")
    public Optional<String> getCancellationDocument() {
        return cancellationDocument;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("canceled_at")
    private Optional<String> _getCanceledAt() {
        return canceledAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof Policy && equalTo((Policy) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(Policy other) {
        return id.equals(other.id)
                && metaData.equals(other.metaData)
                && startDate.equals(other.startDate)
                && providerPolicyId.equals(other.providerPolicyId)
                && providerPolicy.equals(other.providerPolicy)
                && orderStatus.equals(other.orderStatus)
                && approvalStatus.equals(other.approvalStatus)
                && endDate.equals(other.endDate)
                && isClaimed.equals(other.isClaimed)
                && createdAt.equals(other.createdAt)
                && updatedAt.equals(other.updatedAt)
                && clientId.equals(other.clientId)
                && canceledAt.equals(other.canceledAt)
                && invoice.equals(other.invoice)
                && cancellationDocument.equals(other.cancellationDocument);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.id,
                this.metaData,
                this.startDate,
                this.providerPolicyId,
                this.providerPolicy,
                this.orderStatus,
                this.approvalStatus,
                this.endDate,
                this.isClaimed,
                this.createdAt,
                this.updatedAt,
                this.clientId,
                this.canceledAt,
                this.invoice,
                this.cancellationDocument);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> id = Optional.empty();

        private Optional<Map<String, Object>> metaData = Optional.empty();

        private Optional<String> startDate = Optional.empty();

        private Optional<Integer> providerPolicyId = Optional.empty();

        private Optional<String> providerPolicy = Optional.empty();

        private Optional<Integer> orderStatus = Optional.empty();

        private Optional<Integer> approvalStatus = Optional.empty();

        private Optional<String> endDate = Optional.empty();

        private Optional<Boolean> isClaimed = Optional.empty();

        private Optional<String> createdAt = Optional.empty();

        private Optional<String> updatedAt = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> canceledAt = Optional.empty();

        private Optional<String> invoice = Optional.empty();

        private Optional<String> cancellationDocument = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(Policy other) {
            id(other.getId());
            metaData(other.getMetaData());
            startDate(other.getStartDate());
            providerPolicyId(other.getProviderPolicyId());
            providerPolicy(other.getProviderPolicy());
            orderStatus(other.getOrderStatus());
            approvalStatus(other.getApprovalStatus());
            endDate(other.getEndDate());
            isClaimed(other.getIsClaimed());
            createdAt(other.getCreatedAt());
            updatedAt(other.getUpdatedAt());
            clientId(other.getClientId());
            canceledAt(other.getCanceledAt());
            invoice(other.getInvoice());
            cancellationDocument(other.getCancellationDocument());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<Integer> id) {
            this.id = id;
            return this;
        }

        public Builder id(Integer id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "meta_data", nulls = Nulls.SKIP)
        public Builder metaData(Optional<Map<String, Object>> metaData) {
            this.metaData = metaData;
            return this;
        }

        public Builder metaData(Map<String, Object> metaData) {
            this.metaData = Optional.ofNullable(metaData);
            return this;
        }

        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public Builder startDate(Optional<String> startDate) {
            this.startDate = startDate;
            return this;
        }

        public Builder startDate(String startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        @JsonSetter(value = "provider_policy_id", nulls = Nulls.SKIP)
        public Builder providerPolicyId(Optional<Integer> providerPolicyId) {
            this.providerPolicyId = providerPolicyId;
            return this;
        }

        public Builder providerPolicyId(Integer providerPolicyId) {
            this.providerPolicyId = Optional.ofNullable(providerPolicyId);
            return this;
        }

        @JsonSetter(value = "provider_policy", nulls = Nulls.SKIP)
        public Builder providerPolicy(Optional<String> providerPolicy) {
            this.providerPolicy = providerPolicy;
            return this;
        }

        public Builder providerPolicy(String providerPolicy) {
            this.providerPolicy = Optional.ofNullable(providerPolicy);
            return this;
        }

        @JsonSetter(value = "order_status", nulls = Nulls.SKIP)
        public Builder orderStatus(Optional<Integer> orderStatus) {
            this.orderStatus = orderStatus;
            return this;
        }

        public Builder orderStatus(Integer orderStatus) {
            this.orderStatus = Optional.ofNullable(orderStatus);
            return this;
        }

        @JsonSetter(value = "approval_status", nulls = Nulls.SKIP)
        public Builder approvalStatus(Optional<Integer> approvalStatus) {
            this.approvalStatus = approvalStatus;
            return this;
        }

        public Builder approvalStatus(Integer approvalStatus) {
            this.approvalStatus = Optional.ofNullable(approvalStatus);
            return this;
        }

        @JsonSetter(value = "end_date", nulls = Nulls.SKIP)
        public Builder endDate(Optional<String> endDate) {
            this.endDate = endDate;
            return this;
        }

        public Builder endDate(String endDate) {
            this.endDate = Optional.ofNullable(endDate);
            return this;
        }

        @JsonSetter(value = "is_claimed", nulls = Nulls.SKIP)
        public Builder isClaimed(Optional<Boolean> isClaimed) {
            this.isClaimed = isClaimed;
            return this;
        }

        public Builder isClaimed(Boolean isClaimed) {
            this.isClaimed = Optional.ofNullable(isClaimed);
            return this;
        }

        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<String> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(String createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public Builder updatedAt(Optional<String> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder updatedAt(String updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        @JsonSetter(value = "canceled_at", nulls = Nulls.SKIP)
        public Builder canceledAt(Optional<String> canceledAt) {
            this.canceledAt = canceledAt;
            return this;
        }

        public Builder canceledAt(String canceledAt) {
            this.canceledAt = Optional.ofNullable(canceledAt);
            return this;
        }

        public Builder canceledAt(Nullable<String> canceledAt) {
            if (canceledAt.isNull()) {
                this.canceledAt = null;
            } else if (canceledAt.isEmpty()) {
                this.canceledAt = Optional.empty();
            } else {
                this.canceledAt = Optional.of(canceledAt.get());
            }
            return this;
        }

        @JsonSetter(value = "invoice", nulls = Nulls.SKIP)
        public Builder invoice(Optional<String> invoice) {
            this.invoice = invoice;
            return this;
        }

        public Builder invoice(String invoice) {
            this.invoice = Optional.ofNullable(invoice);
            return this;
        }

        @JsonSetter(value = "cancellation_document", nulls = Nulls.SKIP)
        public Builder cancellationDocument(Optional<String> cancellationDocument) {
            this.cancellationDocument = cancellationDocument;
            return this;
        }

        public Builder cancellationDocument(String cancellationDocument) {
            this.cancellationDocument = Optional.ofNullable(cancellationDocument);
            return this;
        }

        public Policy build() {
            return new Policy(
                    id,
                    metaData,
                    startDate,
                    providerPolicyId,
                    providerPolicy,
                    orderStatus,
                    approvalStatus,
                    endDate,
                    isClaimed,
                    createdAt,
                    updatedAt,
                    clientId,
                    canceledAt,
                    invoice,
                    cancellationDocument,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
