/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PolicyAggregates.Builder.class)
public final class PolicyAggregates {
    private final Optional<Integer> totalCount;

    private final Optional<Float> totalPrice;

    private final Optional<Map<String, PolicyMonthAggregate>> byMonth;

    private final Map<String, Object> additionalProperties;

    private PolicyAggregates(
            Optional<Integer> totalCount,
            Optional<Float> totalPrice,
            Optional<Map<String, PolicyMonthAggregate>> byMonth,
            Map<String, Object> additionalProperties) {
        this.totalCount = totalCount;
        this.totalPrice = totalPrice;
        this.byMonth = byMonth;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("total_count")
    public Optional<Integer> getTotalCount() {
        return totalCount;
    }

    @JsonProperty("total_price")
    public Optional<Float> getTotalPrice() {
        return totalPrice;
    }

    /**
     * @return Monthly policy counts and sales totals keyed by YYYY-MM. For issued policies (<code>status=1</code>), buckets use <code>uploaded_at</code> and fall back to <code>created_at</code>.
     */
    @JsonProperty("by_month")
    public Optional<Map<String, PolicyMonthAggregate>> getByMonth() {
        return byMonth;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PolicyAggregates && equalTo((PolicyAggregates) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PolicyAggregates other) {
        return totalCount.equals(other.totalCount)
                && totalPrice.equals(other.totalPrice)
                && byMonth.equals(other.byMonth);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.totalCount, this.totalPrice, this.byMonth);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> totalCount = Optional.empty();

        private Optional<Float> totalPrice = Optional.empty();

        private Optional<Map<String, PolicyMonthAggregate>> byMonth = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PolicyAggregates other) {
            totalCount(other.getTotalCount());
            totalPrice(other.getTotalPrice());
            byMonth(other.getByMonth());
            return this;
        }

        @JsonSetter(value = "total_count", nulls = Nulls.SKIP)
        public Builder totalCount(Optional<Integer> totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        public Builder totalCount(Integer totalCount) {
            this.totalCount = Optional.ofNullable(totalCount);
            return this;
        }

        @JsonSetter(value = "total_price", nulls = Nulls.SKIP)
        public Builder totalPrice(Optional<Float> totalPrice) {
            this.totalPrice = totalPrice;
            return this;
        }

        public Builder totalPrice(Float totalPrice) {
            this.totalPrice = Optional.ofNullable(totalPrice);
            return this;
        }

        /**
         * <p>Monthly policy counts and sales totals keyed by YYYY-MM. For issued policies (<code>status=1</code>), buckets use <code>uploaded_at</code> and fall back to <code>created_at</code>.</p>
         */
        @JsonSetter(value = "by_month", nulls = Nulls.SKIP)
        public Builder byMonth(Optional<Map<String, PolicyMonthAggregate>> byMonth) {
            this.byMonth = byMonth;
            return this;
        }

        public Builder byMonth(Map<String, PolicyMonthAggregate> byMonth) {
            this.byMonth = Optional.ofNullable(byMonth);
            return this;
        }

        public PolicyAggregates build() {
            return new PolicyAggregates(totalCount, totalPrice, byMonth, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
