/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PolicyMonthAggregate.Builder.class)
public final class PolicyMonthAggregate {
    private final Optional<Integer> count;

    private final Optional<Float> totalPrice;

    private final Map<String, Object> additionalProperties;

    private PolicyMonthAggregate(
            Optional<Integer> count, Optional<Float> totalPrice, Map<String, Object> additionalProperties) {
        this.count = count;
        this.totalPrice = totalPrice;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("count")
    public Optional<Integer> getCount() {
        return count;
    }

    @JsonProperty("total_price")
    public Optional<Float> getTotalPrice() {
        return totalPrice;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof PolicyMonthAggregate && equalTo((PolicyMonthAggregate) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(PolicyMonthAggregate other) {
        return count.equals(other.count) && totalPrice.equals(other.totalPrice);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.count, this.totalPrice);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> count = Optional.empty();

        private Optional<Float> totalPrice = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(PolicyMonthAggregate other) {
            count(other.getCount());
            totalPrice(other.getTotalPrice());
            return this;
        }

        @JsonSetter(value = "count", nulls = Nulls.SKIP)
        public Builder count(Optional<Integer> count) {
            this.count = count;
            return this;
        }

        public Builder count(Integer count) {
            this.count = Optional.ofNullable(count);
            return this;
        }

        @JsonSetter(value = "total_price", nulls = Nulls.SKIP)
        public Builder totalPrice(Optional<Float> totalPrice) {
            this.totalPrice = totalPrice;
            return this;
        }

        public Builder totalPrice(Float totalPrice) {
            this.totalPrice = Optional.ofNullable(totalPrice);
            return this;
        }

        public PolicyMonthAggregate build() {
            return new PolicyMonthAggregate(count, totalPrice, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
