/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QuotePrice.Builder.class)
public final class QuotePrice {
    private final Optional<String> quotePriceId;

    private final Optional<Double> deductible;

    private final Optional<Double> subtotal;

    private final Optional<Double> vatPercentage;

    private final Optional<Double> vat;

    private final Optional<Double> total;

    private final Map<String, Object> additionalProperties;

    private QuotePrice(
            Optional<String> quotePriceId,
            Optional<Double> deductible,
            Optional<Double> subtotal,
            Optional<Double> vatPercentage,
            Optional<Double> vat,
            Optional<Double> total,
            Map<String, Object> additionalProperties) {
        this.quotePriceId = quotePriceId;
        this.deductible = deductible;
        this.subtotal = subtotal;
        this.vatPercentage = vatPercentage;
        this.vat = vat;
        this.total = total;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("quote_price_id")
    public Optional<String> getQuotePriceId() {
        return quotePriceId;
    }

    @JsonProperty("deductible")
    public Optional<Double> getDeductible() {
        return deductible;
    }

    @JsonProperty("subtotal")
    public Optional<Double> getSubtotal() {
        return subtotal;
    }

    @JsonProperty("vat_percentage")
    public Optional<Double> getVatPercentage() {
        return vatPercentage;
    }

    @JsonProperty("vat")
    public Optional<Double> getVat() {
        return vat;
    }

    @JsonProperty("total")
    public Optional<Double> getTotal() {
        return total;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QuotePrice && equalTo((QuotePrice) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QuotePrice other) {
        return quotePriceId.equals(other.quotePriceId)
                && deductible.equals(other.deductible)
                && subtotal.equals(other.subtotal)
                && vatPercentage.equals(other.vatPercentage)
                && vat.equals(other.vat)
                && total.equals(other.total);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.quotePriceId, this.deductible, this.subtotal, this.vatPercentage, this.vat, this.total);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> quotePriceId = Optional.empty();

        private Optional<Double> deductible = Optional.empty();

        private Optional<Double> subtotal = Optional.empty();

        private Optional<Double> vatPercentage = Optional.empty();

        private Optional<Double> vat = Optional.empty();

        private Optional<Double> total = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QuotePrice other) {
            quotePriceId(other.getQuotePriceId());
            deductible(other.getDeductible());
            subtotal(other.getSubtotal());
            vatPercentage(other.getVatPercentage());
            vat(other.getVat());
            total(other.getTotal());
            return this;
        }

        @JsonSetter(value = "quote_price_id", nulls = Nulls.SKIP)
        public Builder quotePriceId(Optional<String> quotePriceId) {
            this.quotePriceId = quotePriceId;
            return this;
        }

        public Builder quotePriceId(String quotePriceId) {
            this.quotePriceId = Optional.ofNullable(quotePriceId);
            return this;
        }

        @JsonSetter(value = "deductible", nulls = Nulls.SKIP)
        public Builder deductible(Optional<Double> deductible) {
            this.deductible = deductible;
            return this;
        }

        public Builder deductible(Double deductible) {
            this.deductible = Optional.ofNullable(deductible);
            return this;
        }

        @JsonSetter(value = "subtotal", nulls = Nulls.SKIP)
        public Builder subtotal(Optional<Double> subtotal) {
            this.subtotal = subtotal;
            return this;
        }

        public Builder subtotal(Double subtotal) {
            this.subtotal = Optional.ofNullable(subtotal);
            return this;
        }

        @JsonSetter(value = "vat_percentage", nulls = Nulls.SKIP)
        public Builder vatPercentage(Optional<Double> vatPercentage) {
            this.vatPercentage = vatPercentage;
            return this;
        }

        public Builder vatPercentage(Double vatPercentage) {
            this.vatPercentage = Optional.ofNullable(vatPercentage);
            return this;
        }

        @JsonSetter(value = "vat", nulls = Nulls.SKIP)
        public Builder vat(Optional<Double> vat) {
            this.vat = vat;
            return this;
        }

        public Builder vat(Double vat) {
            this.vat = Optional.ofNullable(vat);
            return this;
        }

        @JsonSetter(value = "total", nulls = Nulls.SKIP)
        public Builder total(Optional<Double> total) {
            this.total = total;
            return this;
        }

        public Builder total(Double total) {
            this.total = Optional.ofNullable(total);
            return this;
        }

        public QuotePrice build() {
            return new QuotePrice(quotePriceId, deductible, subtotal, vatPercentage, vat, total, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
