/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QuoteRequestAggregates.Builder.class)
public final class QuoteRequestAggregates {
    private final Optional<Integer> totalCount;

    private final Optional<Map<String, Integer>> byMonth;

    private final Map<String, Object> additionalProperties;

    private QuoteRequestAggregates(
            Optional<Integer> totalCount,
            Optional<Map<String, Integer>> byMonth,
            Map<String, Object> additionalProperties) {
        this.totalCount = totalCount;
        this.byMonth = byMonth;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("total_count")
    public Optional<Integer> getTotalCount() {
        return totalCount;
    }

    /**
     * @return Monthly quote request counts keyed by YYYY-MM.
     */
    @JsonProperty("by_month")
    public Optional<Map<String, Integer>> getByMonth() {
        return byMonth;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QuoteRequestAggregates && equalTo((QuoteRequestAggregates) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QuoteRequestAggregates other) {
        return totalCount.equals(other.totalCount) && byMonth.equals(other.byMonth);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.totalCount, this.byMonth);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> totalCount = Optional.empty();

        private Optional<Map<String, Integer>> byMonth = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QuoteRequestAggregates other) {
            totalCount(other.getTotalCount());
            byMonth(other.getByMonth());
            return this;
        }

        @JsonSetter(value = "total_count", nulls = Nulls.SKIP)
        public Builder totalCount(Optional<Integer> totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        public Builder totalCount(Integer totalCount) {
            this.totalCount = Optional.ofNullable(totalCount);
            return this;
        }

        /**
         * <p>Monthly quote request counts keyed by YYYY-MM.</p>
         */
        @JsonSetter(value = "by_month", nulls = Nulls.SKIP)
        public Builder byMonth(Optional<Map<String, Integer>> byMonth) {
            this.byMonth = byMonth;
            return this;
        }

        public Builder byMonth(Map<String, Integer> byMonth) {
            this.byMonth = Optional.ofNullable(byMonth);
            return this;
        }

        public QuoteRequestAggregates build() {
            return new QuoteRequestAggregates(totalCount, byMonth, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
