/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QuoteResponseDriversItem.Builder.class)
public final class QuoteResponseDriversItem {
    private final Optional<String> ownerId;

    private final Optional<String> birthdate;

    private final Optional<Integer> drivingPercentage;

    private final Map<String, Object> additionalProperties;

    private QuoteResponseDriversItem(
            Optional<String> ownerId,
            Optional<String> birthdate,
            Optional<Integer> drivingPercentage,
            Map<String, Object> additionalProperties) {
        this.ownerId = ownerId;
        this.birthdate = birthdate;
        this.drivingPercentage = drivingPercentage;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Driver's national ID (10 digits starting with 1, 2, or 7)
     */
    @JsonProperty("owner_id")
    public Optional<String> getOwnerId() {
        return ownerId;
    }

    /**
     * @return Driver's birthdate in YYYY-MM-DD format
     */
    @JsonProperty("birthdate")
    public Optional<String> getBirthdate() {
        return birthdate;
    }

    /**
     * @return Percentage of driving for this driver (25, 50, 75, or 100)
     */
    @JsonProperty("driving_percentage")
    public Optional<Integer> getDrivingPercentage() {
        return drivingPercentage;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QuoteResponseDriversItem && equalTo((QuoteResponseDriversItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QuoteResponseDriversItem other) {
        return ownerId.equals(other.ownerId)
                && birthdate.equals(other.birthdate)
                && drivingPercentage.equals(other.drivingPercentage);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.ownerId, this.birthdate, this.drivingPercentage);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> ownerId = Optional.empty();

        private Optional<String> birthdate = Optional.empty();

        private Optional<Integer> drivingPercentage = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QuoteResponseDriversItem other) {
            ownerId(other.getOwnerId());
            birthdate(other.getBirthdate());
            drivingPercentage(other.getDrivingPercentage());
            return this;
        }

        /**
         * <p>Driver's national ID (10 digits starting with 1, 2, or 7)</p>
         */
        @JsonSetter(value = "owner_id", nulls = Nulls.SKIP)
        public Builder ownerId(Optional<String> ownerId) {
            this.ownerId = ownerId;
            return this;
        }

        public Builder ownerId(String ownerId) {
            this.ownerId = Optional.ofNullable(ownerId);
            return this;
        }

        /**
         * <p>Driver's birthdate in YYYY-MM-DD format</p>
         */
        @JsonSetter(value = "birthdate", nulls = Nulls.SKIP)
        public Builder birthdate(Optional<String> birthdate) {
            this.birthdate = birthdate;
            return this;
        }

        public Builder birthdate(String birthdate) {
            this.birthdate = Optional.ofNullable(birthdate);
            return this;
        }

        /**
         * <p>Percentage of driving for this driver (25, 50, 75, or 100)</p>
         */
        @JsonSetter(value = "driving_percentage", nulls = Nulls.SKIP)
        public Builder drivingPercentage(Optional<Integer> drivingPercentage) {
            this.drivingPercentage = drivingPercentage;
            return this;
        }

        public Builder drivingPercentage(Integer drivingPercentage) {
            this.drivingPercentage = Optional.ofNullable(drivingPercentage);
            return this;
        }

        public QuoteResponseDriversItem build() {
            return new QuoteResponseDriversItem(ownerId, birthdate, drivingPercentage, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
