/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QuoteResponse.Builder.class)
public final class QuoteResponse {
    private final Optional<Integer> ownerId;

    private final Optional<String> phone;

    private final Optional<String> birthdate;

    private final Optional<Integer> carSequenceNumber;

    private final Optional<Boolean> isOwnershipTransfer;

    private final Optional<Double> carEstimatedCost;

    private final Optional<Integer> carModelYear;

    private final Optional<String> startDate;

    private final Optional<List<QuoteResponseDriversItem>> drivers;

    private final Optional<List<QuoteResponseQuotesItem>> quotes;

    private final Optional<String> clientId;

    private final Optional<OffsetDateTime> updatedAt;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<Integer> id;

    private final Map<String, Object> additionalProperties;

    private QuoteResponse(
            Optional<Integer> ownerId,
            Optional<String> phone,
            Optional<String> birthdate,
            Optional<Integer> carSequenceNumber,
            Optional<Boolean> isOwnershipTransfer,
            Optional<Double> carEstimatedCost,
            Optional<Integer> carModelYear,
            Optional<String> startDate,
            Optional<List<QuoteResponseDriversItem>> drivers,
            Optional<List<QuoteResponseQuotesItem>> quotes,
            Optional<String> clientId,
            Optional<OffsetDateTime> updatedAt,
            Optional<OffsetDateTime> createdAt,
            Optional<Integer> id,
            Map<String, Object> additionalProperties) {
        this.ownerId = ownerId;
        this.phone = phone;
        this.birthdate = birthdate;
        this.carSequenceNumber = carSequenceNumber;
        this.isOwnershipTransfer = isOwnershipTransfer;
        this.carEstimatedCost = carEstimatedCost;
        this.carModelYear = carModelYear;
        this.startDate = startDate;
        this.drivers = drivers;
        this.quotes = quotes;
        this.clientId = clientId;
        this.updatedAt = updatedAt;
        this.createdAt = createdAt;
        this.id = id;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The owner’s national ID or Iqama ID
     */
    @JsonProperty("owner_id")
    public Optional<Integer> getOwnerId() {
        return ownerId;
    }

    /**
     * @return The owner's phone number
     */
    @JsonProperty("phone")
    public Optional<String> getPhone() {
        return phone;
    }

    /**
     * @return The owner's birthdate. Hijri for Saudi nationals, Gregorian for others
     */
    @JsonProperty("birthdate")
    public Optional<String> getBirthdate() {
        return birthdate;
    }

    /**
     * @return The car sequence number from 9 digits
     */
    @JsonProperty("car_sequence_number")
    public Optional<Integer> getCarSequenceNumber() {
        return carSequenceNumber;
    }

    /**
     * @return Whether it was a car transfer or not
     */
    @JsonProperty("is_ownership_transfer")
    public Optional<Boolean> getIsOwnershipTransfer() {
        return isOwnershipTransfer;
    }

    /**
     * @return The estimated cost of the car
     */
    @JsonProperty("car_estimated_cost")
    public Optional<Double> getCarEstimatedCost() {
        return carEstimatedCost;
    }

    /**
     * @return The car model year
     */
    @JsonProperty("car_model_year")
    public Optional<Integer> getCarModelYear() {
        return carModelYear;
    }

    /**
     * @return Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request.
     */
    @JsonProperty("start_date")
    public Optional<String> getStartDate() {
        return startDate;
    }

    /**
     * @return List of drivers associated with this quote request. Returned if drivers were provided in the request.
     */
    @JsonProperty("drivers")
    public Optional<List<QuoteResponseDriversItem>> getDrivers() {
        return drivers;
    }

    /**
     * @return An array representing each insurance company quote. Each item has the company name, the prices, and the benefits.
     */
    @JsonProperty("quotes")
    public Optional<List<QuoteResponseQuotesItem>> getQuotes() {
        return quotes;
    }

    /**
     * @return Your own client ID
     */
    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    /**
     * @return In case of an update on this quote, this date will change
     */
    @JsonProperty("updated_at")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return When was the quote requested
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Yasmina ID for the quote. You can use it to delete items or showing it again to the customer
     */
    @JsonProperty("id")
    public Optional<Integer> getId() {
        return id;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QuoteResponse && equalTo((QuoteResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QuoteResponse other) {
        return ownerId.equals(other.ownerId)
                && phone.equals(other.phone)
                && birthdate.equals(other.birthdate)
                && carSequenceNumber.equals(other.carSequenceNumber)
                && isOwnershipTransfer.equals(other.isOwnershipTransfer)
                && carEstimatedCost.equals(other.carEstimatedCost)
                && carModelYear.equals(other.carModelYear)
                && startDate.equals(other.startDate)
                && drivers.equals(other.drivers)
                && quotes.equals(other.quotes)
                && clientId.equals(other.clientId)
                && updatedAt.equals(other.updatedAt)
                && createdAt.equals(other.createdAt)
                && id.equals(other.id);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.ownerId,
                this.phone,
                this.birthdate,
                this.carSequenceNumber,
                this.isOwnershipTransfer,
                this.carEstimatedCost,
                this.carModelYear,
                this.startDate,
                this.drivers,
                this.quotes,
                this.clientId,
                this.updatedAt,
                this.createdAt,
                this.id);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> ownerId = Optional.empty();

        private Optional<String> phone = Optional.empty();

        private Optional<String> birthdate = Optional.empty();

        private Optional<Integer> carSequenceNumber = Optional.empty();

        private Optional<Boolean> isOwnershipTransfer = Optional.empty();

        private Optional<Double> carEstimatedCost = Optional.empty();

        private Optional<Integer> carModelYear = Optional.empty();

        private Optional<String> startDate = Optional.empty();

        private Optional<List<QuoteResponseDriversItem>> drivers = Optional.empty();

        private Optional<List<QuoteResponseQuotesItem>> quotes = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<Integer> id = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QuoteResponse other) {
            ownerId(other.getOwnerId());
            phone(other.getPhone());
            birthdate(other.getBirthdate());
            carSequenceNumber(other.getCarSequenceNumber());
            isOwnershipTransfer(other.getIsOwnershipTransfer());
            carEstimatedCost(other.getCarEstimatedCost());
            carModelYear(other.getCarModelYear());
            startDate(other.getStartDate());
            drivers(other.getDrivers());
            quotes(other.getQuotes());
            clientId(other.getClientId());
            updatedAt(other.getUpdatedAt());
            createdAt(other.getCreatedAt());
            id(other.getId());
            return this;
        }

        /**
         * <p>The owner’s national ID or Iqama ID</p>
         */
        @JsonSetter(value = "owner_id", nulls = Nulls.SKIP)
        public Builder ownerId(Optional<Integer> ownerId) {
            this.ownerId = ownerId;
            return this;
        }

        public Builder ownerId(Integer ownerId) {
            this.ownerId = Optional.ofNullable(ownerId);
            return this;
        }

        /**
         * <p>The owner's phone number</p>
         */
        @JsonSetter(value = "phone", nulls = Nulls.SKIP)
        public Builder phone(Optional<String> phone) {
            this.phone = phone;
            return this;
        }

        public Builder phone(String phone) {
            this.phone = Optional.ofNullable(phone);
            return this;
        }

        /**
         * <p>The owner's birthdate. Hijri for Saudi nationals, Gregorian for others</p>
         */
        @JsonSetter(value = "birthdate", nulls = Nulls.SKIP)
        public Builder birthdate(Optional<String> birthdate) {
            this.birthdate = birthdate;
            return this;
        }

        public Builder birthdate(String birthdate) {
            this.birthdate = Optional.ofNullable(birthdate);
            return this;
        }

        /**
         * <p>The car sequence number from 9 digits</p>
         */
        @JsonSetter(value = "car_sequence_number", nulls = Nulls.SKIP)
        public Builder carSequenceNumber(Optional<Integer> carSequenceNumber) {
            this.carSequenceNumber = carSequenceNumber;
            return this;
        }

        public Builder carSequenceNumber(Integer carSequenceNumber) {
            this.carSequenceNumber = Optional.ofNullable(carSequenceNumber);
            return this;
        }

        /**
         * <p>Whether it was a car transfer or not</p>
         */
        @JsonSetter(value = "is_ownership_transfer", nulls = Nulls.SKIP)
        public Builder isOwnershipTransfer(Optional<Boolean> isOwnershipTransfer) {
            this.isOwnershipTransfer = isOwnershipTransfer;
            return this;
        }

        public Builder isOwnershipTransfer(Boolean isOwnershipTransfer) {
            this.isOwnershipTransfer = Optional.ofNullable(isOwnershipTransfer);
            return this;
        }

        /**
         * <p>The estimated cost of the car</p>
         */
        @JsonSetter(value = "car_estimated_cost", nulls = Nulls.SKIP)
        public Builder carEstimatedCost(Optional<Double> carEstimatedCost) {
            this.carEstimatedCost = carEstimatedCost;
            return this;
        }

        public Builder carEstimatedCost(Double carEstimatedCost) {
            this.carEstimatedCost = Optional.ofNullable(carEstimatedCost);
            return this;
        }

        /**
         * <p>The car model year</p>
         */
        @JsonSetter(value = "car_model_year", nulls = Nulls.SKIP)
        public Builder carModelYear(Optional<Integer> carModelYear) {
            this.carModelYear = carModelYear;
            return this;
        }

        public Builder carModelYear(Integer carModelYear) {
            this.carModelYear = Optional.ofNullable(carModelYear);
            return this;
        }

        /**
         * <p>Requested policy start date in YYYY-MM-DD. Returned if provided in the quote request.</p>
         */
        @JsonSetter(value = "start_date", nulls = Nulls.SKIP)
        public Builder startDate(Optional<String> startDate) {
            this.startDate = startDate;
            return this;
        }

        public Builder startDate(String startDate) {
            this.startDate = Optional.ofNullable(startDate);
            return this;
        }

        /**
         * <p>List of drivers associated with this quote request. Returned if drivers were provided in the request.</p>
         */
        @JsonSetter(value = "drivers", nulls = Nulls.SKIP)
        public Builder drivers(Optional<List<QuoteResponseDriversItem>> drivers) {
            this.drivers = drivers;
            return this;
        }

        public Builder drivers(List<QuoteResponseDriversItem> drivers) {
            this.drivers = Optional.ofNullable(drivers);
            return this;
        }

        /**
         * <p>An array representing each insurance company quote. Each item has the company name, the prices, and the benefits.</p>
         */
        @JsonSetter(value = "quotes", nulls = Nulls.SKIP)
        public Builder quotes(Optional<List<QuoteResponseQuotesItem>> quotes) {
            this.quotes = quotes;
            return this;
        }

        public Builder quotes(List<QuoteResponseQuotesItem> quotes) {
            this.quotes = Optional.ofNullable(quotes);
            return this;
        }

        /**
         * <p>Your own client ID</p>
         */
        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        /**
         * <p>In case of an update on this quote, this date will change</p>
         */
        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * <p>When was the quote requested</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>Yasmina ID for the quote. You can use it to delete items or showing it again to the customer</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<Integer> id) {
            this.id = id;
            return this;
        }

        public Builder id(Integer id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        public QuoteResponse build() {
            return new QuoteResponse(
                    ownerId,
                    phone,
                    birthdate,
                    carSequenceNumber,
                    isOwnershipTransfer,
                    carEstimatedCost,
                    carModelYear,
                    startDate,
                    drivers,
                    quotes,
                    clientId,
                    updatedAt,
                    createdAt,
                    id,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
