/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.yasminaai.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QuoteResponseQuotesItem.Builder.class)
public final class QuoteResponseQuotesItem {
    private final Optional<String> companyName;

    private final Optional<List<QuotePrice>> prices;

    private final Optional<List<Benefit>> benefits;

    private final Map<String, Object> additionalProperties;

    private QuoteResponseQuotesItem(
            Optional<String> companyName,
            Optional<List<QuotePrice>> prices,
            Optional<List<Benefit>> benefits,
            Map<String, Object> additionalProperties) {
        this.companyName = companyName;
        this.prices = prices;
        this.benefits = benefits;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("company_name")
    public Optional<String> getCompanyName() {
        return companyName;
    }

    /**
     * @return An array representing each price. This will have the premium and the deductible
     */
    @JsonProperty("prices")
    public Optional<List<QuotePrice>> getPrices() {
        return prices;
    }

    /**
     * @return An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional
     */
    @JsonProperty("benefits")
    public Optional<List<Benefit>> getBenefits() {
        return benefits;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QuoteResponseQuotesItem && equalTo((QuoteResponseQuotesItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QuoteResponseQuotesItem other) {
        return companyName.equals(other.companyName) && prices.equals(other.prices) && benefits.equals(other.benefits);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.companyName, this.prices, this.benefits);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> companyName = Optional.empty();

        private Optional<List<QuotePrice>> prices = Optional.empty();

        private Optional<List<Benefit>> benefits = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QuoteResponseQuotesItem other) {
            companyName(other.getCompanyName());
            prices(other.getPrices());
            benefits(other.getBenefits());
            return this;
        }

        @JsonSetter(value = "company_name", nulls = Nulls.SKIP)
        public Builder companyName(Optional<String> companyName) {
            this.companyName = companyName;
            return this;
        }

        public Builder companyName(String companyName) {
            this.companyName = Optional.ofNullable(companyName);
            return this;
        }

        /**
         * <p>An array representing each price. This will have the premium and the deductible</p>
         */
        @JsonSetter(value = "prices", nulls = Nulls.SKIP)
        public Builder prices(Optional<List<QuotePrice>> prices) {
            this.prices = prices;
            return this;
        }

        public Builder prices(List<QuotePrice> prices) {
            this.prices = Optional.ofNullable(prices);
            return this;
        }

        /**
         * <p>An array representing the different benefits offered by the company. Some of them are free and comes with the insurance, some are paid and optional</p>
         */
        @JsonSetter(value = "benefits", nulls = Nulls.SKIP)
        public Builder benefits(Optional<List<Benefit>> benefits) {
            this.benefits = benefits;
            return this;
        }

        public Builder benefits(List<Benefit> benefits) {
            this.benefits = Optional.ofNullable(benefits);
            return this;
        }

        public QuoteResponseQuotesItem build() {
            return new QuoteResponseQuotesItem(companyName, prices, benefits, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
