/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.yasminaai.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class QuoteResponseQuotesItemType {
    public static final QuoteResponseQuotesItemType TPL = new QuoteResponseQuotesItemType(Value.TPL, "TPL");

    public static final QuoteResponseQuotesItemType COMPREHENSIVE =
            new QuoteResponseQuotesItemType(Value.COMPREHENSIVE, "Comprehensive");

    private final Value value;

    private final String string;

    QuoteResponseQuotesItemType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof QuoteResponseQuotesItemType
                        && this.string.equals(((QuoteResponseQuotesItemType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TPL:
                return visitor.visitTpl();
            case COMPREHENSIVE:
                return visitor.visitComprehensive();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static QuoteResponseQuotesItemType valueOf(String value) {
        switch (value) {
            case "TPL":
                return TPL;
            case "Comprehensive":
                return COMPREHENSIVE;
            default:
                return new QuoteResponseQuotesItemType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TPL,

        COMPREHENSIVE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTpl();

        T visitComprehensive();

        T visitUnknown(String unknownType);
    }
}
